### ISSUE TITLE
Issue connecting to MQTT Broker

### ISSUE THREAD

**Issue by woodartworx** [wez/govee2mqtt#106]
### Govee Device SKU

H706A

### Govee2MQTT Version

2024.01.21-33e8cd7c

### Describe the issue

Error: connecting to mqtt broker 192.168.1.100:1883

This is strange, I am using eclipse MQTT broker v2.0.18  on a Synology docker container.  I have other addon's in HA connected to MQTT using the username / pw that work perfectly and I can connect directly to the MQTT broker with the username / pw using MQTT Explorer but your addon will not connect...

### Startup Diagnostics

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
GOVEE_API_KEY=REDACTED
GOVEE_MQTT_HOST=192.168.1.100
GOVEE_TEMPERATURE_SCALE=F
++ cd /app
GOVEE_EMAIL=REDACTED
GOVEE_PASSWORD=REDACTED
GOVEE_MQTT_PASSWORD=REDACTED
++ exec /app/govee serve
GOVEE_MQTT_USER=mqtt_govee
GOVEE_MQTT_PORT=1883
[2024-01-22T21:55:51 INFO  govee::commands::serve] Starting service. version 2024.01.21-33e8cd7c
[2024-01-22T21:55:51 INFO  govee::commands::serve] Querying platform API for device list
[2024-01-22T21:55:51 INFO  govee::commands::serve] Querying undocumented API for device + room list
[2024-01-22T21:55:51 INFO  govee::service::iot] Connected to IoT: CONNACK code 0: Connection Accepted.
[2024-01-22T21:55:51 INFO  govee::commands::serve] Starting LAN discovery
[2024-01-22T21:55:51 INFO  govee::commands::serve] Waiting 10 seconds for LAN API discovery
[2024-01-22T21:55:51 INFO  govee::service::iot] IoT (re)connected with status CONNACK code 0: Connection Accepted.
[2024-01-22T21:56:01 INFO  govee::commands::serve] Devices returned from Govee's APIs
[2024-01-22T21:56:01 INFO  govee::commands::serve] Permanent Lights Pro (28:14:F5:C0:12:B5:BE:1C H706A)
[2024-01-22T21:56:01 INFO  govee::commands::serve]   Platform API: devices.types.light. supports_rgb=true supports_brightness=true
[2024-01-22T21:56:01 INFO  govee::commands::serve]                 color_temp=Some((2000, 9000)) segment_rgb=Some(0..24)
[2024-01-22T21:56:01 INFO  govee::commands::serve]   Undoc: room=None supports_iot=true ble_only=false
[2024-01-22T21:56:01 INFO  govee::commands::serve] 
Error: connecting to mqtt broker 192.168.1.100:1883

Caused by:
    broker rejected connection

Stack backtrace:
   0: anyhow::context::<impl anyhow::Context<T,E> for core::result::Result<T,E>>::with_context
   1: govee::commands::serve::ServeCommand::run::{{closure}}
   2: govee::Args::run::{{closure}}
   3: tokio::runtime::park::CachedParkThread::block_on
   4: tokio::runtime::runtime::Runtime::block_on
   5: govee::main
   6: std::sys_common::backtrace::__rust_begin_short_backtrace
   7: std::rt::lang_start::{{closure}}
   8: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:284:13
   9: std::panicking::try::do_call
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40
  10: std::panicking::try
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19
  11: std::panic::catch_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14
  12: std::rt::lang_start_internal::{{closure}}
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:148:48
  13: std::panicking::try::do_call
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40
  14: std::panicking::try
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19
  15: std::panic::catch_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14
  16: std::rt::lang_start_internal
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:148:20
  17: std::rt::lang_start
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

### Additional Logs

On the MQTT Broker log I get the following error:

New connection from 192.168.1.95:49842 on port 1883.
Client <unknown> disconnected due to protocol error.

**Comment by wez** [comment]
Govee2MQTT uses eclipse libmosquitto 2.0.9 so compatibility should be generally good.
Do you have any interesting settings in the broker that might influence this?
What else can you tell me about the broker and the HA machine? Are they different CPU architectures?

**Comment by woodartworx** [comment]
Believe I have found the issue...
 I commented the following line from the mosquitto.conf file

# client id required MQTT 3.1.1 and MQTT 5
#allow_zero_length_clientid false

Your addon now connects to the broker.
