### ISSUE TITLE
Support for H6199 TV Ambilight Video Mode

### ISSUE THREAD

**Issue by IamTheLoki** [wez/govee2mqtt#111]
### Govee Device SKU

H6199

### Govee2MQTT Version

2024.01.24-ea3cd430

### Describe the issue

Is it possible to add Support for the Video Mode from the H6199 like for the Music Modes in other Devices?

### Startup Diagnostics

No Video Mode under Scenes

**Comment by wez** [comment]
Not directly on the light entity, but check out: https://github.com/wez/govee2mqtt/blob/main/docs/FAQ.md#how-do-i-enable-video-effects-for-a-light

**Comment by IamTheLoki** [comment]
Thank you!
