### ISSUE TITLE
Entities gets resetted after update

### ISSUE THREAD

**Issue by marcelpetersen** [wez/govee2mqtt#12]
I noticed that after every update of the addon (sometimes even when restarting), all my govee devices gets resetted. 
**That means:**
- If I renamed them, they went back to their original name
- If I assigned them to an area, they are not assigned anymore

Feels like the devices gets removed and new ones will be created

Is that issue related to the addon?
And is there a way to prevent that?

**Comment by wez** [comment]
This should be resolved in the latest release

**Comment by marcelpetersen** [comment]
Tested it. Looks good! Thanks for that fast fix :)
