### ISSUE TITLE
Web UI

### ISSUE THREAD

**Issue by djezlee** [wez/govee2mqtt#123]
### Govee Device SKU

N/A

### Govee2MQTT Version

2024.01.24-ea3cd430

### Describe the issue

Does the Web UI work for anyone... or is it just mine that won't open?

### Startup Diagnostics

N/A

**Comment by aatkins2github** [comment]
Same issue here.
This *homeassistant* page can’t be found
No webpage was found for the web address: 
http://*homeassistantserver*:8056/assets/index.html
HTTP ERROR 404

**Comment by Shura1oplot** [comment]
Same issue here.

**Comment by d13g0m0nt3s** [comment]
Same here

**Comment by Claudio19876** [comment]
Same here

**Comment by tommi00** [comment]
Same here

**Comment by pfeifferch** [comment]
Same here

**Comment by tismofied** [comment]
Just discovered this amazing addon today. I am afraid to say that the webui is not working here either.
Core  : 2024.2.3
Supervisor : 2024.02.0
Operating System : 11.5
Frontend : 20240207.1
Addon Current version: 2024.01.24-ea3cd430

**Comment by sdaltons1** [comment]
So yeah we can all see it, it doesn't do anything for any of us, I'm pretty sure he didn't mean to have it show up. And from using other addons that do use a web UI, I can't really see how this addon could utilize it.

**Comment by sbeier23** [comment]
I tracked down the issue in HA. It seems, that the complete assets folder inside the container in /app is missing.

![image](https://github.com/wez/govee2mqtt/assets/74077294/af56b31c-30dc-4c17-b509-6c1f5fefcde4)

when you manually download the assets into the container, its working as above. but after a restart it will be gone again ;-)

**Comment by skl111** [comment]
@wez have you any idea why this is happening?

**Comment by wez** [comment]
I think this may be fixed in the latest version. I can't easily directly test it because there is some proxy stuff happening in my local setup that prevents me from doing so, and I don't currently have time to wrangle it.
