### ISSUE TITLE
Not all DIY Scenes available

### ISSUE THREAD

**Issue by marcelpetersen** [wez/govee2mqtt#13]
I noticed, that at least one of my DIY Scenes is not available in HA. I'm wondering if there is a reason for this or if it could be some kind of bug?
For testing purposes, I created several DIY scenes and all of them showed up properly

**Comment by marcelpetersen** [comment]
Made some further testing. There are multiple Scenes that are not available. I dont know why. i cant see any pattern

**Comment by marcelpetersen** [comment]
Understood. Hopefully the api gets some bugfixes. Exactly my needed scenes are not available 😄

**Comment by wez** [comment]
As a workaround, you can try creating a one-click scene that sets the scenes on the devices you want. That scene should then show up in the overall list of scenes in hass.

**Comment by marcelpetersen** [comment]
Thanks, will try this!

**Comment by marcelpetersen** [comment]
Can you explain how to do it? Thought you meant the tap to run thing, but this does not work. So I thing I’m missing something

**Comment by wez** [comment]
Can you share what you tried and what you saw?

**Comment by marcelpetersen** [comment]
I thought I tried the one click scene thing. But I think I did not understood it. Where I have to set up this one click scene thing in the Govee app? 
All I did was configuring a tap to run action, but I think this is wrong

**Comment by wez** [comment]
Yeah, it's the Tap-to-Run section in the app (it's called OneClick in the API).  Entries there should show up as Scenes in the addon. You may need to restart the addon to make it reconsider and add the scenes to hass.

Once done you can find them in hass either by:

* Go to the `Govee To MQTT` device and see the list there
* Go to `Settings` `Automations & scenes` `Scenes`

**Comment by marcelpetersen** [comment]
I tried it via the tap to run thing. Unfortunately I didn't received any new scenes. Neither in the effect section of the device nor under the scenes section. I added screenshots, what i did in the app:
![IMG_3121](https://github.com/wez/govee2mqtt/assets/9086896/6c372240-602f-402b-bffd-05fa7ea98c71)
![IMG_3122](https://github.com/wez/govee2mqtt/assets/9086896/15fac0d2-236e-4f24-882f-44144697640f)

**Comment by wez** [comment]
If you have `docker` available to you, can you run:

```console
$ docker run --rm ghcr.io/wez/govee2mqtt /app/govee undoc dump-one-click --govee-email $GOVEE_EMAIL --govee-password $GOVEE_PASSWORD
```

and share the output with me? That will show what is returned from the one-click api

**Comment by marcelpetersen** [comment]
just checked everything: The Scene is now available. Dont know why it took so much time. i restarted multiple times without any effect and now it is working

**Comment by wez** [comment]
Sounds like the old value was sitting in the cache, so the resolution here is: provide a way to clear that cache

**Comment by marcelpetersen** [comment]
Yes. Just adjusted the tap to run. Now the old tap to runs seems to stick in the cache (won’t removed) and new ones don’t get added

**Comment by wez** [comment]
I've added a Purge Caches button to the `Govee to MQTT` device; clicking it will delete the cache database then re-register all entities with HASS.

Don't click it too much in a short time: another user got locked out of their govee account for 24 hours for unusual login activity when the cache was not enabled for them!

**Comment by marcelpetersen** [comment]
Nice! After hitting the button, my new one click event was available. But the old ones, which i deleted in the app are still present? Maybe i just need to wait some time?

**Comment by wez** [comment]
Ah, detecting deletes is a bit of a PITA at the moment.
govee2mqtt is stateless (aside from caches), so it doesn't remember that it previously told hass about that scene.
To remove it, I think you'll need to go into the `Govee to MQTT` device and delete it, then either wait a minute for it to get re-registered, or restart the addon.

**Comment by marcelpetersen** [comment]
yes thats it. i removed the govee to mqtt device, after that i just restarted. govee to mqtt entity was coming back with the correct one click scenes!

**Comment by wez** [comment]
Great, let's close this then!
