### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by littlej956** [wez/govee2mqtt#138]
### Govee Device SKU

multiple devices

### Govee2MQTT Version

2024.01.24-ea3cd430

### Describe the issue

Logging not working, i have triple checked user/password, i have even changed password but no luck. I have the api key on email.  How to debug this, can anyone help ? 

### Startup Diagnostics

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
GOVEE_API_KEY=REDACTED
GOVEE_TEMPERATURE_SCALE=C
GOVEE_EMAIL=REDACTED
GOVEE_PASSWORD=REDACTED
++ cd /app
++ exec /app/govee serve
[2024-02-19T19:31:36 INFO  govee::commands::serve] Starting service. version 2024.01.24-ea3cd430
[2024-02-19T19:31:36 INFO  govee::commands::serve] Querying platform API for device list
[2024-02-19T19:31:36 INFO  govee::commands::serve] Querying undocumented API for device + room list
Error: request https://app2.govee.com/account/rest/account/v1/login status 200: OK: parsing https://app2.govee.com/account/rest/account/v1/login response: Failed with status 400 Bad Request Bad Request: Request to https://app2.govee.com/account/rest/account/v1/login failed with code 400 Bad Request Incorrect password. Full response: {"status":400,"message":"Incorrect password"}

Stack backtrace:
   0: anyhow::error::<impl anyhow::Error>::msg
   1: anyhow::__private::format_err
   2: govee::cache::cache_get::{{closure}}
   3: govee::undoc_api::GoveeUndocumentedApi::login_account_cached::{{closure}}
   4: govee::commands::serve::ServeCommand::run::{{closure}}
   5: govee::Args::run::{{closure}}
   6: tokio::runtime::park::CachedParkThread::block_on
   7: tokio::runtime::runtime::Runtime::block_on
   8: govee::main
   9: std::sys_common::backtrace::__rust_begin_short_backtrace
  10: std::rt::lang_start::{{closure}}
  11: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:284:13
  12: std::panicking::try::do_call
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40
  13: std::panicking::try
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19
  14: std::panic::catch_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14
  15: std::rt::lang_start_internal::{{closure}}
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:148:48
  16: std::panicking::try::do_call
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40
  17: std::panicking::try
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19
  18: std::panic::catch_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14
  19: std::rt::lang_start_internal
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:148:20
  20: std::rt::lang_start
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

### Anything else?

Any idea how to go on ?

**Comment by littlej956** [comment]
nvmd, apparently was a govee api issue, i have tried now with same configuration and all works as expected.

**Comment by floodwayprintco** [comment]
> nvmd, apparently was a govee api issue, i have tried now with same configuration and all works as expected.

Can I ask what the issue was? Was it just downtime? I am having the same issue with a brand new API key and definitely the correct password.

**Comment by littlej956** [comment]
> > nvmd, apparently was a govee api issue, i have tried now with same configuration and all works as expected.
> 
> Can I ask what the issue was? Was it just downtime? I am having the same issue with a brand new API key and definitely the correct password.

Yeah, i think api was down or something because after some it started to work.
