### ISSUE TITLE
Humidifier Looses Connection

### ISSUE THREAD

**Issue by Zixxorb** [wez/govee2mqtt#158]
### Govee Device SKU

H7140

### Govee2MQTT Version

2024.01.24-ea3cd430

### Describe the issue

Humidifier looses connection and will not reconnect. Can see device for a day or so after initial set up then stays gray and does not stay connected. Addon says start when clicking on addon even tho Start on boot is enabled (unsure if this is the actual issue and watchdog is enabled as well.)

### Startup Diagnostics

Unsure if right log...

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
++ cd /app
GOVEE_API_KEY=REDACTED
GOVEE_TEMPERATURE_SCALE=F
GOVEE_EMAIL=REDACTED
GOVEE_PASSWORD=REDACTED
++ exec /app/govee serve
[2024-03-27T21:34:38 INFO  govee::commands::serve] Starting service. version 2024.01.24-ea3cd430
[2024-03-27T21:34:38 INFO  govee::commands::serve] Querying platform API for device list
[2024-03-27T21:34:38 INFO  govee::commands::serve] Querying undocumented API for device + room list
[2024-03-27T21:34:41 INFO  govee::service::iot] Connected to IoT: CONNACK code 0: Connection Accepted.
[2024-03-27T21:34:41 INFO  govee::commands::serve] Starting LAN discovery
[2024-03-27T21:34:41 INFO  govee::commands::serve] Waiting 10 seconds for LAN API discovery
[2024-03-27T21:34:41 INFO  govee::service::iot] IoT (re)connected with status CONNACK code 0: Connection Accepted.
[2024-03-27T21:34:51 INFO  govee::commands::serve] Devices returned from Govee's APIs
[2024-03-27T21:34:51 INFO  govee::commands::serve] Humidifier (15:D1:D4:AD:FC:84:65:9C H7140)
[2024-03-27T21:34:51 INFO  govee::commands::serve]   Platform API: devices.types.humidifier. supports_rgb=true supports_brightness=true
[2024-03-27T21:34:51 INFO  govee::commands::serve]                 color_temp=None segment_rgb=None
[2024-03-27T21:34:51 INFO  govee::commands::serve]   Undoc: room=None supports_iot=true ble_only=false
[2024-03-27T21:34:51 INFO  govee::commands::serve] 
Error: Please specify the mqtt broker either via the --mqtt-host parameter or by setting $GOVEE_MQTT_HOST

Stack backtrace:
   0: std::backtrace_rs::backtrace::libunwind::trace
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1: std::backtrace_rs::backtrace::trace_unsynchronized
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2: std::backtrace::Backtrace::create
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/backtrace.rs:331:13
   3: anyhow::error::<impl anyhow::Error>::msg
   4: govee::service::hass::HassArguments::mqtt_host
   5: govee::commands::serve::ServeCommand::run::{{closure}}
   6: govee::Args::run::{{closure}}
   7: tokio::runtime::park::CachedParkThread::block_on
   8: tokio::runtime::runtime::Runtime::block_on
   9: govee::main
  10: std::sys_common::backtrace::__rust_begin_short_backtrace
  11: std::rt::lang_start::{{closure}}
  12: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:284:13
  13: std::panicking::try::do_call
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40
  14: std::panicking::try
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19
  15: std::panic::catch_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14
  16: std::rt::lang_start_internal::{{closure}}
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:148:48
  17: std::panicking::try::do_call
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40
  18: std::panicking::try
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19
  19: std::panic::catch_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14
  20: std::rt::lang_start_internal
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:148:20
  21: std::rt::lang_start
  22: main
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

### Additional Logs

[mqtt-c764bbab89793d539196727872b074c1-Humidifier-f69ca0171fdb4592741cfd1139f0d507.json](https://github.com/wez/govee2mqtt/files/14794447/mqtt-c764bbab89793d539196727872b074c1-Humidifier-f69ca0171fdb4592741cfd1139f0d507.json)

### Anything else?

First time submitting one of these, apologies if I did this wrong.

**Comment by wez** [comment]
> [2024-03-27T21:34:51 INFO govee::commands::serve]
Error: Please specify the mqtt broker either via the --mqtt-host parameter or by setting $GOVEE_MQTT_HOST

This suggests that no mqtt broker is available, and that you either:

* Need to install and start the MQTT addon; see https://github.com/wez/govee2mqtt/blob/main/docs/ADDON.md#set-up-mqtt
* Need to fill out the mqtt host box to reference your existing external mqtt broker in the addon configuration screen; see the bottom-most image on https://github.com/wez/govee2mqtt/blob/main/docs/ADDON.md

**Comment by Zixxorb** [comment]
So I have MQTT addon installed. Seems the auto start on boot wasn't sticking in [it's/HA's] last update and now seems to be.

Thanks for the help.
