### ISSUE TITLE
Run standalone without HA?

### ISSUE THREAD

**Issue by m-elias** [wez/govee2mqtt#172]
Can this run apart from Home Assistant? I'd like to simply publish my Govee's data to mqtt topics.

**Comment by wez** [comment]
Yes; just run it standalone. https://github.com/wez/govee2mqtt/blob/main/docs/DOCKER.md

**Comment by m-elias** [comment]
I'm running Docker on unRaid and this is all very new to me.
I assume I can skip #1 (MQTT integration in Home Assistant).

I have copied the skeleton env example and filled in the particulars for my mqtt broker, govee account/api key, timezone etc. It's saved in the /config path as govee2mqtt.env.

Here's my Docker config for this container:
![image](https://github.com/wez/govee2mqtt/assets/27897240/aa3426ff-8f65-41df-8bdd-40df184758d6)

I'm not sure what to do with docker-compose.yml, I don't think I need it as I've entered the parameters in the config UI.

I get the following error in the logs, it looks like it's not loading my env file?
[2024-04-17T09:15:49 INFO  govee::commands::serve] Starting service. version 2024.02.05-4c4fa0db
[2024-04-17T09:15:49 INFO  govee::commands::serve] Starting LAN discovery
[2024-04-17T09:15:49 INFO  govee::commands::serve] Waiting 10 seconds for LAN API discovery
[2024-04-17T09:15:59 INFO  govee::commands::serve] Devices returned from Govee's APIs
Error: Please specify the mqtt broker either via the --mqtt-host parameter or by setting $GOVEE_MQTT_HOST

sanitized govee2mqtt.env
GOVEE_EMAIL=email@domain.com
GOVEE_PASSWORD=email_pw
GOVEE_API_KEY=api_key_from_govee_email
GOVEE_MQTT_HOST=host_ip_Addr
GOVEE_MQTT_PORT=1883
GOVEE_MQTT_USER=user_name
GOVEE_MQTT_PASSWORD=user_pw
GOVEE_TEMPERATURE_SCALE=C
RUST_LOG_STYLE=always
#RUST_LOG=govee=trace
TZ=America/Chicago

I also tried changing the env_file key to env-file.

**Comment by m-elias** [comment]
I now see a gv2mqtt topic with the one wifi temp/hum sensor's data on my broker. Is it possible to get data from my other sensors? I have H5054 & H5105 sensors. These are the ones lists as "Unknown device type. Cannot map to Home Assistant."

**Comment by wez** [comment]
Glad to hear that you've got things up and running.
The unknown device types are generally things that we cannot communicate with and are unsupported.
See also:
* https://github.com/wez/govee2mqtt/issues/61

**Comment by dnestico** [comment]
I know this issue is closed but a bit of a noob here sorry but I think I did all the MQTT stuff correctly and it seems connected but no devices are showing up in MQTT addon Home Assistant, pls help what am I doing wrong here.

<img width="1140" alt="Screenshot 2024-11-19 at 1 39 30 PM" src="https://github.com/user-attachments/assets/9efe954a-3ecf-4d9f-8199-ce87114bb8b1">

<img width="1107" alt="Screenshot 2024-11-19 at 1 41 27 PM" src="https://github.com/user-attachments/assets/b748e05a-4e97-469e-b4c5-9501219c189d">
