### ISSUE TITLE
Add-on won't start

### ISSUE THREAD

**Issue by mpc2314** [wez/govee2mqtt#21]
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
GOVEE_API_KEY=REDACTED
GOVEE_MQTT_HOST=core-mosquitto
GOVEE_EMAIL=REDACTED
GOVEE_PASSWORD=REDACTED
GOVEE_MQTT_PASSWORD=REDACTED
GOVEE_LAN_BROADCAST_ALL=false
GOVEE_MQTT_USER=addons
GOVEE_MQTT_PORT=1883
++ cd /app
++ exec /app/govee serve
[2024-01-06T21:24:24 INFO  govee::commands::serve] Starting service. version 2024.01.06-5915ee93
[2024-01-06T21:24:24 INFO  govee::commands::serve] Querying platform API for device list
[2024-01-06T21:24:25 INFO  govee::commands::serve] Querying undocumented API for device + room list
Error: request https://app2.govee.com/device/rest/devices/v1/list status 200: OK

Caused by:
    0: parsing https://app2.govee.com/device/rest/devices/v1/list response
    1: govee::undoc_api::DevicesResponse devices[63].deviceExt.deviceSettings: govee::undoc_api::DeviceSettings govee::undoc_api::DeviceSettings missing field `sku` at line 1 column 249. Input: 

*there is a whole bunch of code here but I had to cut it out because I got an error saying my post in this message was too long*

Stack backtrace:
   0: std::backtrace_rs::backtrace::libunwind::trace
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1: std::backtrace_rs::backtrace::trace_unsynchronized
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2: std::backtrace::Backtrace::create
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/backtrace.rs:331:13
   3: anyhow::error::<impl anyhow::Error>::msg
   4: govee::platform_api::from_json
   5: govee::undoc_api::GoveeUndocumentedApi::get_device_list::{{closure}}
   6: govee::commands::serve::ServeCommand::run::{{closure}}
   7: govee::Args::run::{{closure}}
   8: tokio::runtime::park::CachedParkThread::block_on
   9: govee::main
  10: std::sys_common::backtrace::__rust_begin_short_backtrace
  11: std::rt::lang_start::{{closure}}
  12: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:284:13
  13: std::panicking::try::do_call
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40
  14: std::panicking::try
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19
  15: std::panic::catch_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14
  16: std::rt::lang_start_internal::{{closure}}
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:148:48
  17: std::panicking::try::do_call
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40
  18: std::panicking::try
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19
  19: std::panic::catch_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14
  20: std::rt::lang_start_internal
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:148:20
  21: std::rt::lang_start
  22: main
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by wez** [comment]
Please attach the json from the log output as an attachment to this issue; I need that to understand the shape of the data and resolve this.

**Comment by mpc2314** [comment]
[log.json](https://github.com/wez/govee2mqtt/files/13852523/log.json)
Thanks.  See attached.

**Comment by wez** [comment]
I've updated the addon so that it should be able to get past that now; please update it and let me know how it goes!

**Comment by mpc2314** [comment]
[log2.json](https://github.com/wez/govee2mqtt/files/13853612/log2.json)
I updated the addon, but I got another error trying to get it started.

**Comment by wez** [comment]
update and try again?

**Comment by mpc2314** [comment]
I got it to work by removing my Govee username and password and just leaving my API Key.  Once I restarted the addon with just the API Key, everything populated.  Thanks for all of your help.

**Comment by wez** [comment]
I'm interested in seeing and resolving any errors you experience with the govee username and password configured

**Comment by mpc2314** [comment]
[Log 3.json](https://github.com/wez/govee2mqtt/files/13854605/Log.3.json)
I was having strange behavior without my username and password.  I could toggle a device off and the light would turn off, but the toggle in HA would switch back over to on, but the light was still off.  I added my username and password back and got the same really long error again.  I attached the log file.

**Comment by wez** [comment]
The latest version of the addon should resolve this, please let me know when you get a chance!

**Comment by mpc2314** [comment]
The update you just posted 2024.01.09-ab0af6b7 seems to have fixed my issues.  I am logged in with my credentials and API and have access to all of my devices.

**Comment by wez** [comment]
Great!
