### ISSUE TITLE
Image on dockerhub ?

### ISSUE THREAD

**Issue by zalmael** [wez/govee2mqtt#211]
Hi,

I'm really interested with this project (already a user of the previous integration on HA), and I would like to know if it's planned to publish govee2mqtt on dockerhub ?
Indeed, I have a device on which I can run docker images, but only those available from dockerhub.

I'm not sure what are the prerequisites, and maybe you have your own reasons not to do it, but I had to ask :)

Thank you very much.

Pierre.

**Comment by wez** [comment]
No plans to do this; it's more engineering work and maintenance effort, which I cannot afford, and shouldn't be necessary since the images are already publicly available via the GH container repo.

**Comment by zalmael** [comment]
Yeah, I totally understand, as I said, I don't really know what the effort are, and I asked only cause I have a pretty limited hardware on this subject.
Maybe in the future they will open other possibilites to build containers. Or maybe I will go for another more openened hardware. Thanks for your reply and your work 👍
