### ISSUE TITLE
Hostname Resolution Error

### ISSUE THREAD

**Issue by F1zzyD** [wez/govee2mqtt#217]
### Govee Device SKU

N/A

### Govee2MQTT Version

Latest

### Describe the issue

I am running govee2mqtt in a docker alongside hass core and [mosquitto](https://mosquitto.org/). Mosquitto and hass boot up fine and so does govee2mqtt... except after the 10 second delay it throws a huge block of text and the error "Hostname resolution error: Try again". I've spent three hours double checking everything and my credentials are correct, but govee2mqtt refuses to work. However, I am able to get MQTT installed through the Hass UI and it sees mosquitto at 127.0.0.1:1883

I'm attaching the log from govee2mqtt, the compose.yml, and the mosquitto.conf for reference.

### Startup Diagnostics

[log.txt](https://github.com/user-attachments/files/15801064/log.txt)

### Home Assistant Logs

N/A

### Anything else?

[compose.txt](https://github.com/user-attachments/files/15801065/compose.txt)
[mosquitto.txt](https://github.com/user-attachments/files/15801066/mosquitto.txt)

**Comment by F1zzyD** [comment]
I just changed MQTT_BROKER to 127.0.0.1 and I'm still getting "Hostname resolution error: Try again". That didn't seem to do anything.

HASS Core accepts MQTT being set to 127.0.0.1 and I see the Govee integration pop up, but it refuses to make any sort of connection.
________________________________

**Comment by F1zzyD** [comment]
I did some more tinkering and now I have more errors than I did before. I went back and redid everything outlined in [the main guide for docker](https://github.com/sukesh-ak/setup-mosquitto-with-docker) and I'm finding several inconsistencies/conflicting instructions:

- Step 5 has me make the default network as `mqtt5-network`, however when moving forward with 5.1 we delete this and change it to `caddy-mqtt`. Which is it?
- I have my own domain through Cloudfare. Do I need to follow step 5.1? If so...
- The step for DNS Setup does not tell us were to put the code `mqtt.domain.com  A  <public-IP-address-for-MQTT-instance>`. Where am I supposed to put this?
- When running with `docker compose up`, I get this warning in the logs: `{"level":"warn","ts":1718217729.2704155,"msg":"Caddyfile input is not formatted; run 'caddy fmt --overwrite' to fix inconsistencies","adapter":"caddyfile","file":"/etc/caddy/Caddyfile","line":2}`. This is from when I copied and pasted the code included  in "Content of configuration file called 'Caddyfile'

I've included the full log from caddy here and my updated compose.yml. I am still getting "Hostname resolution error: Try again" from govee2mqtt as well.

[compose.txt](https://github.com/user-attachments/files/15809679/compose.txt)
[log.txt](https://github.com/user-attachments/files/15809680/log.txt)

**Comment by wez** [comment]
Troubleshooting your caddy, cloudflare and docker installation is out of scope for me; sorry, but you'll need to continue on your own.

**Comment by GarisonLotus** [comment]
@F1zzyD  - I don't know if you ever solved this... but I ran into the exact same issue today. I solved it by updating the .env file to include:

GOVEE_MQTT_HOST=127.0.0.1
MQTT_BROKER=127.0.0.1

-- cut --


then it started working. It doesn't need to have a valid hostname.

**Comment by cmdshft** [comment]
I'm having the same issue.

```
[2024-07-05T05:11:11Z INFO  govee::commands::serve] Starting service. version 2024.06.18-dc01fbc7
[2024-07-05T05:11:11Z INFO  govee::commands::serve] Starting LAN discovery
[2024-07-05T05:11:11Z INFO  govee::commands::serve] Waiting 10 seconds for LAN API discovery
[2024-07-05T05:11:21Z INFO  govee::commands::serve] Devices returned from Govee's APIs
Error: Please specify the mqtt broker either via the --mqtt-host parameter or by setting $GOVEE_MQTT_HOST
Stack backtrace:
   0: std::backtrace::Backtrace::create
   1: anyhow::error::<impl anyhow::Error>::msg
   2: govee::service::hass::HassArguments::mqtt_host
   3: govee::commands::serve::ServeCommand::run::{{closure}}
   4: govee::Args::run::{{closure}}
   5: tokio::runtime::park::CachedParkThread::block_on
   6: tokio::runtime::context::runtime::enter_runtime
   7: tokio::runtime::runtime::Runtime::block_on
   8: govee::main
   9: std::sys_common::backtrace::__rust_begin_short_backtrace
  10: std::rt::lang_start::{{closure}}
  11: std::rt::lang_start_internal
  12: main
```

I am using
```
GOVEE_MQTT_HOST=127.0.0.1
MQTT_BROKER=127.0.0.1
```

![image](https://github.com/wez/govee2mqtt/assets/8571823/36b13542-c889-4ff1-abc7-ec90180267a8)

![image](https://github.com/wez/govee2mqtt/assets/8571823/d74e33a7-ab02-4fae-81a2-05e21b2841fc)

Log from mqtt shows:

```
1720154349: mosquitto version 2.0.18 starting
1720154349: Config loaded from /mosquitto/config/mosquitto.conf.
1720154349: Opening ipv4 listen socket on port 1883.
1720154349: Opening ipv6 listen socket on port 1883.
1720154349: Opening websockets listen socket on port 9001.
1720154349: mosquitto version 2.0.18 running
1720154383: New connection from 172.18.0.1:38164 on port 1883.
1720154383: Client auto-9E86C469-4F09-4ABC-73FE-D6C67C1B6B04 disconnected, not authorised.
1720154387: New connection from 172.18.0.1:52334 on port 1883.
1720154387: Client auto-28926D98-795E-37B8-3B1A-DE22E3468355 disconnected, not authorised.
1720154404: New connection from 172.18.0.1:44408 on port 1883.
1720154404: New client connected from 172.18.0.1:44408 as auto-B56393B7-A16C-02CC-1D16-133E160CEC9D (p2, c1, k60, u'cmdshft').
1720154440: Client auto-B56393B7-A16C-02CC-1D16-133E160CEC9D disconnected.
1720154449: New connection from 172.18.0.1:60312 on port 1883.
1720154449: New client connected from 172.18.0.1:60312 as auto-5C1ABB3B-A85C-8D23-A6A1-8E5D348BBF6D (p2, c1, k60, u'cmdshft').
1720154449: Client auto-5C1ABB3B-A85C-8D23-A6A1-8E5D348BBF6D disconnected.
1720154507: New connection from 10.0.0.35:45789 on port 1883.
1720154507: New client connected from 10.0.0.35:45789 as 3Ca219FYluVntBcPtOkhNT (p2, c1, k60, u'cmdshft').
1720154507: Client 3Ca219FYluVntBcPtOkhNT disconnected.
1720154507: New connection from 10.0.0.35:58695 on port 1883.
1720154507: New client connected from 10.0.0.35:58695 as 79gltOgDbn5YKaxR7mnlRq (p2, c1, k60, u'cmdshft').
1720154602: New connection from 10.0.0.35:54077 on port 1883.
1720154602: New client connected from 10.0.0.35:54077 as 5ZRLvDMOtgo142TQ8XhRMO (p5, c1, k60, u'cmdshft').
1720154602: Client 5ZRLvDMOtgo142TQ8XhRMO disconnected.
1720154784: Client 79gltOgDbn5YKaxR7mnlRq disconnected.
1720154784: New connection from 10.0.0.35:57897 on port 1883.
1720154784: New client connected from 10.0.0.35:57897 as 7G7bucucATKXmVOQWNAGVR (p5, c1, k60, u'cmdshft').
1720155199: Client 7G7bucucATKXmVOQWNAGVR disconnected.
1720155199: New connection from 10.0.0.35:36257 on port 1883.
1720155199: New client connected from 10.0.0.35:36257 as 2wUlb8cKUr8isS6FTSDiPT (p5, c1, k60, u'cmdshft').
1720155489: Client 2wUlb8cKUr8isS6FTSDiPT disconnected.
1720155489: New connection from 10.0.0.35:44317 on port 1883.
1720155489: New client connected from 10.0.0.35:44317 as 53HVvguZ8oIzInhBkCciX6 (p5, c1, k60, u'cmdshft').
1720156150: Saving in-memory database to /mosquitto/data//mosquitto.db.
```
