### ISSUE TITLE
H7143 Humidifier

### ISSUE THREAD

**Issue by vortexcomp** [wez/govee2mqtt#22]
It's not fair to call this an issue since I know this is designed for the Govee lights, but I thought I would ask in case this was in the works or possible in the near future. 

I have said humidifier and MQTT is recognizing it as follows: 

```
[2024-01-06T21:03:52 INFO  govee::commands::serve] Humidifier (Removed MAC) sku=H7143
[2024-01-06T21:03:52 INFO  govee::commands::serve]   Platform API: devices.types.humidifier. supports_rgb=true supports_brightness=true
[2024-01-06T21:03:52 INFO  govee::commands::serve]                 color_temp=None segment_rgb=None
[2024-01-06T21:03:52 INFO  govee::commands::serve]   Undoc: room=None supports_iot=true ble_only=false
```

While the Govee app doesn't allow me to enable local LAN, I did configure the add-on with my credentials and API key. I can turn the unit on/off, change it's color, as well as enable/disable the light and warm mist settings.

The settings I cannot change are: 

- Mode: Manual/Auto
-- Target % for Auto
-- Auto Stop disable
- Mist Level: 40 - 80% 
-  Display: Enable/Disable

Is there any way I could go about adding those options through the MQTT humidifier element or through this add-on? I'm in the beginning of my MQTT journey so I'm not sure what diagnostics to run to be of further help. 

If there is any information I can provide that will be helpful please let me know.

**Comment by wez** [comment]
I just picked up an H7160 today. The APIs won't let me control its lights (boo!) but I do see the mode stuff there.
I'll likely be working on enabling that here in govee2mqtt tomorrow.

**Comment by vortexcomp** [comment]
Funny that we're reversed, that would be amazing! I was in the process of returning this in favor of a tuya compatible one - but that one doesn't have the lights, the warm mist or several other things. 

Will stand by and if there is any information I can provide I'm happy to do so.

**Comment by wez** [comment]
it's not really reversed: neither of us can control the modes, but only you can control the lights.
I do see the metadata for the mode control in the responses I'm getting from govee though, so it should be possible to make that work.
One thing that I am disappointed about is that the API doesn't return any of the useful sensor data for my device (https://developer.govee.com/discuss/6599ec2ebbfb7000701e87f8)

**Comment by wez** [comment]
I've published an updated version that supports the H7160. It's possible that some or all functionality for your device may now be present.  I'd recommend deleting the humidifier device from under the MQTT integration section and then restarting the new version of the addon, and then please let me know how it shows up in home assistant and which functions work/don't work.

**Comment by sdaltons1** [comment]
For context (or not lol)...

Everything looks good with my H7141 humidifier.  

I am going to post similar in the smart fan ticket and could also help with the humidifier and purifier if you are willing to take a look. 

I think the changes you made for the humidifier got all these other devices pretty close. I can see the different "parameter" options as entities for each device, so it may just be a matter of HA needing to understand these are the modes for the respective devices. 

![IMG_0431](https://github.com/wez/govee2mqtt/assets/93367436/6ffcf780-241a-453c-bf1d-4dd76f076784)

**Comment by sdaltons1** [comment]
![IMG_0434](https://github.com/wez/govee2mqtt/assets/93367436/da4f148f-e646-48b6-a38e-60fd762dcf2f)

**Comment by sdaltons1** [comment]
The manual option gives a slider from 1-8 which corresponds with the mist level of the device. Would be cool to incorporate this into the device screenshot I posted before, but not a huge deal either way.

**Comment by wez** [comment]
The way the H7160 works is:
* Auto Mode - you can set the target humidity percentage
* Manual Mode - you can set the level of the mister
* Custom - unknown/complex: combines scheduling with mister control

The way that HASS humidifier entity works is:
* You can control/monitor the target humidity
* You can optionally report the current humidity (my device doesn't support this, so there is no logic to report it)

So the Humidifier UI in HA can only realistically set the value for the Auto Mode.  The manual mister level has to be a separate entity because it just doesn't map to a humidity percentage.

I opted to hide both the additional number sliders for Auto and Custom for the H7160 because:
* Auto - the slider range is an offset scale that can't easily be automatically mapped into the correct percentage range in the context of the standalone number slider. We don't really "know" what it is in that context and can't easily interpret it without leaving a nasty code smell in that part of the code.
* Custom - I have no idea how to decode or extract those modes, but really, if you were doing something smart like that in HASS you would automate the Manual level directly in HASS and won't need control over the custom parameter.

If the H7143 works similarly to my H7160, then I can apply the same logic to how things get mapped into HASS.

**Comment by sdaltons1** [comment]
I don't have a govee hygrometer paired to mine but looking at the options, auto mode seems to work the same way. 

Definitely correct about manual mode and I understand your reasoning with the sliders. And completely agree custom mode seems far too complicated lol. 

So I think the functionality between the two models is a match. 

Regarding what you asked me to do for the fan, can I just enter that into the HA terminal? If so I'll play with it in a bit.

**Comment by wez** [comment]
> So I think the functionality between the two models is a match. Oh you put H7143 in your reply but mine is H7141. Just pointing it out in case.

OK, I'll make an update that treats those 3 devices similarly then.

> Regarding what you asked me to do for the fan, can I just enter that into the HA terminal? If so I'll play with it in a bit.

I'm not sure; I don't run HAOS so I don't know what the access to docker is like in that environment.
Those `http-control` commands can be run from any device with docker, so if you have a separate box that can run docker, you can do so without fretting about the HASS system.

**Comment by vortexcomp** [comment]
I'm a little limited on time this week but I removed the entity, updated and restarted. This is what it looks like in HASS:

![image](https://github.com/wez/govee2mqtt/assets/38778236/6c11538a-1d73-481e-be0d-e9c0a1b6cd1c)

The follow still/currently work: 

- Power On/Off
- Warm Mist On/Off
- Light On/Off
- HASS Card shows current target humidity, power state, mode
- HASS Card now accurately reflects the set color

Not working: 
-  Setting mode manual/auto
- Change the Target Humidity
- Set color 
- Change Brightness 

I don't see any errors in the logs - which I have set to verbose. Regarding the setting the color I wonder if it's related to the ability to set scenes as well as colors. This is listed with the command: 

```
[2024-01-09T13:06:54 DEBUG govee::service::iot] Packet { sku: Some("H7143"), device: Some("MAC"), cmd: 
Some("ptReal"), msg: None, state: StateUpdate { on_off: None, brightness: None, color: None, color_temperature_kelvin: None, 
sku: None, device: None }, op: Some(OpData { command: [SetHumidifierNightlight(HumidifierNightlightParams { on: false, r: 0, 
g: 0, b: 0, brightness: 0 })] }) }
```

I see this warn - and am including the subsequent traces:
```
[2024-01-09T13:15:20 WARN  govee::hass_mqtt::enumerator] Do something about Mode nightlightScene for Humidifier 
(MAC) DeviceCapability { kind: Mode, instance: "nightlightScene", parameters: Some(Enum { options: 
[EnumOption { name: "Forest", value: Number(1), extras: {} }, EnumOption { name: "Ocean", value: Number(2), extras: {} }, 
EnumOption { name: "Wetland", value: Number(3), extras: {} }, EnumOption { name: "Leisurely", value: Number(4), extras: {} }, 
EnumOption { name: "ASleep", value: Number(5), extras: {} }] }), alarm_type: None, event_state: None }
[2024-01-09T13:15:20 TRACE govee::hass_mqtt::light] LightConfig::notify_state: state is DeviceState { on: true, online: None, 
kelvin: 0, color: DeviceColor { r: 139, g: 0, b: 255 }, brightness: 13, scene: None, source: "AWS IoT API", updated: 2024-01-
09T21:15:19.112582452Z }
[2024-01-09T13:15:20 TRACE govee::service::hass] gv2mqtt/light/MAC/state -> {"brightness":13,"color":
{"b":255,"g":0,"r":139},"color_mode":"rgb","effect":null,"state":"ON"}
[2024-01-09T13:15:20 TRACE govee::service::hass] gv2mqtt/humidifier/MAC/state -> ON
[2024-01-09T13:15:20 TRACE govee::service::hass] gv2mqtt/humidifier/MAC/notify-target -> 72
[2024-01-09T13:15:20 TRACE govee::service::hass] gv2mqtt/humidifier/MAC/notify-mode -> Manual
[2024-01-09T13:15:20 TRACE govee::service::hass] gv2mqtt/switch/MAC/powerSwitch/state -> ON
[2024-01-09T13:15:20 TRACE govee::hass_mqtt::switch] CapabilitySwitch::notify_state: didn't find state for Humidifier (MAC) warmMistToggle
[2024-01-09T13:15:20 TRACE govee::service::hass] gv2mqtt/number/MAC/state/manual -> 0
[2024-01-09T13:15:20 TRACE govee::service::hass] gv2mqtt/number/MAC/state/auto -> 0
[2024-01-09T13:15:20 TRACE govee::hass_mqtt::switch] CapabilitySwitch::notify_state: didn't find state for Humidifier (MAC) nightlightToggle
```

_MAC scrubbed from data out of habit_

**Comment by wez** [comment]
To flesh out the bits that aren't being controlled, I'd appreciate it you could capture the packets that are being sent via the IoT MQTT channel.

Set the debug level to `govee::service::iot=debug,info` so that you're not overwhelmed.
Then go into the Govee app and change a parameter and you should see some notifications show up in the log.
Please capture those together with what you set in the app, so that we have a mapping.
It can be helpful to vary the value in a mode (eg: change the target humidity or level to a couple of different values) so that it is easier to spot which parts of the packet are changing and how the value is mapped in.

Thanks!

**Comment by vortexcomp** [comment]
I think this is the bulk of them: 

### Color Change

```
[2024-01-09T23:22:00 DEBUG govee::service::iot] Packet { sku: Some("H7143"), device: Some("MAC"), cmd: 
Some("multiSync"), msg: None, state: StateUpdate { on_off: None, brightness: None, color: None, color_temperature_kelvin: None,
sku: None, device: None }, op: Some(OpData { command: [NotifyHumidifierNightlight(HumidifierNightlightParams { on: true, r: 100, 
g: 0, b: 0, brightness: 1 }), NotifyHumidifierNightlight(HumidifierNightlightParams { on: true, r: 0, g: 0, b: 255, brightness: 13 })], 
mode_value: [], sleep_value: [], wakeup_value: [], timer_value: [] }) }
```

### Brightness Change

```
[2024-01-09T23:23:12 DEBUG govee::service::iot] Packet { sku: Some("H7143"), device: Some("MAC"), cmd: 
Some("multiSync"), msg: None, state: StateUpdate { on_off: None, brightness: None, color: None, color_temperature_kelvin: 
None, sku: None, device: None }, op: Some(OpData { command: [NotifyHumidifierNightlight(HumidifierNightlightParams { on: 
true, r: 39, g: 0, b: 0, brightness: 1 }), NotifyHumidifierNightlight(HumidifierNightlightParams { on: true, r: 139, g: 0, b: 255, 
brightness: 13 })], mode_value: [], sleep_value: [], wakeup_value: [], timer_value: [] }) }
```

### Scene Change

```
[2024-01-09T23:25:17 DEBUG govee::service::iot] Packet { sku: Some("H7143"), device: Some("MAC"), cmd: 
Some("multiSync"), msg: None, state: StateUpdate { on_off: None, brightness: None, color: None, color_temperature_kelvin: 
None, sku: None, device: None }, op: Some(OpData { command: [NotifyHumidifierNightlight(HumidifierNightlightParams { on: 
true, r: 39, g: 0, b: 0, brightness: 1 }), NotifyHumidifierNightlight(HumidifierNightlightParams { on: true, r: 0, g: 1, b: 0, brightness: 
19 })], mode_value: [], sleep_value: [], wakeup_value: [], timer_value: [] }) }

[2024-01-09T23:25:17 WARN  govee::hass_mqtt::enumerator] Do something about Mode nightlightScene for Humidifier 
(MAC) DeviceCapability { kind: Mode, instance: "nightlightScene", parameters: Some(Enum { options: 
[EnumOption { name: "Forest", value: Number(1), extras: {} }, EnumOption { name: "Ocean", value: Number(2), extras: {} }, 
EnumOption { name: "Wetland", value: Number(3), extras: {} }, EnumOption { name: "Leisurely", value: Number(4), extras: {} }, 
EnumOption { name: "ASleep", value: Number(5), extras: {} }] }), alarm_type: None, event_state: None }
```

_I'm not sure how practical the scene change will be, regardless of the scene I picked it seems as if the app has preset values for each scene and sends a standard rgb commands_

### Switch To Auto Mode

```
[2024-01-09T23:27:56 DEBUG govee::service::iot] Packet { sku: Some("H7143"), device: Some("MAC"), cmd: 
Some("status"), msg: None, state: StateUpdate { on_off: Some(1), brightness: None, color: None, color_temperature_kelvin: 
None, sku: None, device: None }, op: Some(OpData { command: [Generic([AA, 12, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 
00, 00, 00, 00, B8]), NotifyHumidifierTimer { on: false }, NotifyHumidifierMode { mode: 3, param: 0 }, 
NotifyHumidifierManualMode { param: 9 }, Generic([AA, 05, 02, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, AD]), 
NotifyHumidifierAutoMode { param: TargetHumidity(200) }, Generic([AA, 16, 01, FF, FF, FF, FF, 00, 00, 00, 00, 00, 00, 00, 00, 00, 
00, 00, 00, BD]), NotifyHumidifierNightlight(HumidifierNightlightParams { on: true, r: 39, g: 0, b: 0, brightness: 1 }), 
NotifyHumidifierNightlight(HumidifierNightlightParams { on: true, r: 0, g: 1, b: 0, brightness: 19 }), Generic([AA, 08, 00, 00, 00, 00, 
00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, A2]), Generic([AA, 10, 81, 03, 45, 3B, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 
00, 46]), Generic([AA, 1F, 00, 0D, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, B9]), Generic([AA, 1E, 01, 02, 01, 00, 74, 
00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, C2]), Generic([AA, 1E, 01, 02, 02, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 
B5]), Generic([AA, 17, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, BD])], mode_value: [], sleep_value: [], 
wakeup_value: [], timer_value: [] }) }
```

### Change Target Humidity

```
[2024-01-09T23:31:52 DEBUG govee::service::iot] Packet { sku: Some("H7143"), device: Some("MAC"), cmd:
Some("status"), msg: None, state: StateUpdate { on_off: Some(1), brightness: None, color: None, color_temperature_kelvin: 
None, sku: None, device: None }, op: Some(OpData { command: [Generic([AA, 12, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 
00, 00, 00, 00, B8]), NotifyHumidifierTimer { on: false }, NotifyHumidifierMode { mode: 3, param: 0 }, 
NotifyHumidifierManualMode { param: 9 }, Generic([AA, 05, 02, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, AD]), 
NotifyHumidifierAutoMode { param: TargetHumidity(168) }, Generic([AA, 16, 01, FF, FF, FF, FF, 00, 00, 00, 00, 00, 00, 00, 00, 00, 
00, 00, 00, BD]), NotifyHumidifierNightlight(HumidifierNightlightParams { on: true, r: 39, g: 0, b: 0, brightness: 1 }), 
NotifyHumidifierNightlight(HumidifierNightlightParams { on: true, r: 0, g: 1, b: 0, brightness: 19 }), Generic([AA, 08, 00, 00, 00, 00, 
00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, A2]), Generic([AA, 10, 81, 03, 46, 21, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 
00, 5F]), Generic([AA, 1F, 00, 0D, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, B9]), Generic([AA, 1E, 01, 02, 01, 00, 74, 
00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, C2]), Generic([AA, 1E, 01, 02, 02, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 
B5]), Generic([AA, 17, 00, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, BC])], mode_value: [], sleep_value: [], 
wakeup_value: [], timer_value: [] }) }
```

_On my device the range is 40 - 80%. I changed it to both max and min and it looks like it's range is 168 - 208 as an int_

### Switch to Manual Mode

```
[2024-01-09T23:38:06 DEBUG govee::service::iot] Packet { sku: Some("H7143"), device: Some("MAC"), cmd: 
Some("multiSync"), msg: None, state: StateUpdate { on_off: None, brightness: None, color: None, color_temperature_kelvin: 
None, sku: None, device: None }, op: Some(OpData { command: [Generic([3A, 05, 01, 09, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 
00, 00, 00, 00, 37])], mode_value: [], sleep_value: [], wakeup_value: [], timer_value: [] }) }
```

### Min Mist Lvl

```
[2024-01-09T23:39:25 DEBUG govee::service::iot] Packet { sku: Some("H7143"), device: Some("MAC"), cmd: 
Some("multiSync"), msg: None, state: StateUpdate { on_off: None, brightness: None, color: None, color_temperature_kelvin: 
None, sku: None, device: None }, op: Some(OpData { command: [Generic([3A, 05, 01, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 
00, 00, 00, 00, 3F])], mode_value: [], sleep_value: [], wakeup_value: [], timer_value: [] }) }
```
### Max Mist Lvl

```
[2024-01-09T23:40:02 DEBUG govee::service::iot] Packet { sku: Some("H7143"), device: Some("MAC"), cmd: 
Some("multiSync"), msg: None, state: StateUpdate { on_off: None, brightness: None, color: None, color_temperature_kelvin: 
None, sku: None, device: None }, op: Some(OpData { command: [Generic([3A, 05, 01, 09, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 
00, 00, 00, 00, 37])], mode_value: [], sleep_value: [], wakeup_value: [], timer_value: [] }) }
```

_Mist level for me is 1 - 9_

### Disable Lock

```
[2024-01-09T23:41:42 DEBUG govee::service::iot] Packet { sku: Some("H7143"), device: Some("MAC"), cmd: 
Some("multiSync"), msg: None, state: StateUpdate { on_off: None, brightness: None, color: None, color_temperature_kelvin: 
None, sku: None, device: None }, op: Some(OpData { command: [Generic([AA, 1F, 00, 0D, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 
00, 00, 00, 00, B9])], mode_value: [], sleep_value: [], wakeup_value: [], timer_value: [] }) }
```
### Enable Lock

```
[2024-01-09T23:42:22 DEBUG govee::service::iot] Packet { sku: Some("H7143"), device: Some("MAC"), cmd: 
Some("multiSync"), msg: None, state: StateUpdate { on_off: None, brightness: None, color: None, color_temperature_kelvin: 
None, sku: None, device: None }, op: Some(OpData { command: [Generic([AA, 1F, 01, 0D, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 
00, 00, 00, 00, B8])], mode_value: [], sleep_value: [], wakeup_value: [], timer_value: [] }) }
```

### Disable Auto Stop

```
[2024-01-09T23:44:34 DEBUG govee::service::iot] Packet { sku: Some("H7143"), device: Some("MAC"), cmd: 
Some("multiSync"), msg: None, state: StateUpdate { on_off: None, brightness: None, color: None, color_temperature_kelvin: 
None, sku: None, device: None }, op: Some(OpData { command: [Generic([3A, 05, 03, 28, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 
00, 00, 00, 00, 14])], mode_value: [], sleep_value: [], wakeup_value: [], timer_value: [] }) }
```
### Enable Auto Stop

```
[2024-01-09T23:43:22 DEBUG govee::service::iot] Packet { sku: Some("H7143"), device: Some("MAC"), cmd: 
Some("multiSync"), msg: None, state: StateUpdate { on_off: None, brightness: None, color: None, color_temperature_kelvin: 
None, sku: None, device: None }, op: Some(OpData { command: [Generic([3A, 05, 03, A8, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 
00, 00, 00, 00, 94])], mode_value: [], sleep_value: [], wakeup_value: [], timer_value: [] }) }
```

Hope this helps!

**Comment by wez** [comment]
For color and brightness, did the values in the logged packet match the color and brightness that you set?

**Comment by vortexcomp** [comment]
I can test a few more to be sure but yes, just my simple blue, green and red tests all logged the appropriate 255 in their respective channels.

**Comment by wez** [comment]
I made some changes in the latest version that will try to use the platform API for this device; it seemed like the same iot packets didn't help you in previous versions, so the current state is that it won't try to use iot at all for this device.

Since the metadata for your device doesn't provide a way to control the nightlight, that won't be controllable.

However, the work modes should hopefully work now.  Please let me know how you get on with this!

**Comment by wez** [comment]
@davide169 if you're asking about a different product, please file a separate issue, thanks!
