### ISSUE TITLE
No Controll H6052

### ISSUE THREAD

**Issue by Leopoldpaul** [wez/govee2mqtt#23]
The integration is able to get the state of the device but is not able to change the settings of the device.
Worked fine with the old Lan Hacs integration.
[log.txt](https://github.com/wez/govee2mqtt/files/13853758/log.txt)
The following messages are shown in the log after trying to control the device:
Location: src/service/device.rs:132

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                              ⋮ 8 frames hidden ⋮                               
 9: core::str::slice_error_fail_rt::hd81691d7c6137e94
    at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/str/mod.rs:<unknown line>
10: core::str::slice_error_fail::h6008385fc9f6cb2d
    at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/str/mod.rs:88
11: govee::service::device::Device::computed_name::he1fca1ad06ebdc47
    at <unknown source file>
12: govee::service::state::State::resolve_device::{{closure}}::h0a1aed3a1f746c8e
    at <unknown source file>
13: govee::service::hass::mqtt_light_command::{{closure}}::h16a7c03e9caf5ec3
    at <unknown source file>
14: <F as mosquitto_rs::router::MakeDispatcher<(T1,T2,T3),S>>::make_dispatcher::{{closure}}::{{closure}}::hcbcbf8a5a8d57480
    at <unknown source file>
15: govee::service::hass::run_mqtt_loop::{{closure}}::{{closure}}::h4d9f9d26d0c79369
    at <unknown source file>
16: tokio::runtime::task::core::Core<T,S>::poll::hc3da23ac17cfba86
    at <unknown source file>
17: tokio::runtime::task::harness::Harness<T,S>::poll::hff91d27950ac5306
    at <unknown source file>
18: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::h961cf5efdcf2db09
    at <unknown source file>
19: tokio::runtime::scheduler::multi_thread::worker::Context::run::hf90ea69a2ddd14a2
    at <unknown source file>
20: tokio::runtime::context::runtime::enter_runtime::ha9d7c1eeefa2dc6c
    at <unknown source file>
21: tokio::runtime::scheduler::multi_thread::worker::run::h2936d0c1dd3c8a93
    at <unknown source file>
22: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll::h80934512d6265755
    at <unknown source file>
23: tokio::runtime::task::core::Core<T,S>::poll::hee995c4e5369f63a
    at <unknown source file>
24: tokio::runtime::task::harness::Harness<T,S>::poll::h94f2d1261558f98b
    at <unknown source file>
25: tokio::runtime::blocking::pool::Inner::run::hfbf2f285523fc11d
    at <unknown source file>
26: std::sys_common::backtrace::__rust_begin_short_backtrace::h7dcbf5c86af169d0
    at <unknown source file>
27: core::ops::function::FnOnce::call_once{{vtable.shim}}::h65a7992c4166b435
    at <unknown source file>
28: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h616b14acddf02c74
    at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/alloc/src/boxed.rs:2007
29: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h7092a971a33bba02
    at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/alloc/src/boxed.rs:2007
30: std::sys::unix::thread::Thread::new::thread_start::hbad4e975c1ab7550
    at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys/unix/thread.rs:108
The application panicked (crashed).
Message:  byte index 18 is out of bounds of `cef142b0b354995f`
Location: src/service/device.rs:132

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                              ⋮ 8 frames hidden ⋮                               
 9: core::str::slice_error_fail_rt::hd81691d7c6137e94
    at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/str/mod.rs:<unknown line>
10: core::str::slice_error_fail::h6008385fc9f6cb2d
    at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/str/mod.rs:88
11: govee::service::device::Device::computed_name::he1fca1ad06ebdc47
    at <unknown source file>
12: govee::service::state::State::resolve_device::{{closure}}::h0a1aed3a1f746c8e
    at <unknown source file>
13: govee::service::hass::mqtt_light_command::{{closure}}::h16a7c03e9caf5ec3
    at <unknown source file>
14: <F as mosquitto_rs::router::MakeDispatcher<(T1,T2,T3),S>>::make_dispatcher::{{closure}}::{{closure}}::hcbcbf8a5a8d57480
    at <unknown source file>
15: govee::service::hass::run_mqtt_loop::{{closure}}::{{closure}}::h4d9f9d26d0c79369
    at <unknown source file>
16: tokio::runtime::task::core::Core<T,S>::poll::hc3da23ac17cfba86
    at <unknown source file>
17: tokio::runtime::task::harness::Harness<T,S>::poll::hff91d27950ac5306
    at <unknown source file>
18: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::h961cf5efdcf2db09
    at <unknown source file>
19: tokio::runtime::scheduler::multi_thread::worker::Context::run::hf90ea69a2ddd14a2
    at <unknown source file>
20: tokio::runtime::context::runtime::enter_runtime::ha9d7c1eeefa2dc6c
    at <unknown source file>
21: tokio::runtime::scheduler::multi_thread::worker::run::h2936d0c1dd3c8a93
    at <unknown source file>
22: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll::h80934512d6265755
    at <unknown source file>
23: tokio::runtime::task::core::Core<T,S>::poll::hee995c4e5369f63a
    at <unknown source file>
24: tokio::runtime::task::harness::Harness<T,S>::poll::h94f2d1261558f98b
    at <unknown source file>
25: tokio::runtime::blocking::pool::Inner::run::hfbf2f285523fc11d
    at <unknown source file>
26: std::sys_common::backtrace::__rust_begin_short_backtrace::h7dcbf5c86af169d0
    at <unknown source file>
27: core::ops::function::FnOnce::call_once{{vtable.shim}}::h65a7992c4166b435
    at <unknown source file>
28: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h616b14acddf02c74
    at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/alloc/src/boxed.rs:2007
29: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h7092a971a33bba02
    at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/alloc/src/boxed.rs:2007
30: std::sys::unix::thread::Thread::new::thread_start::hbad4e975c1ab7550
    at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys/unix/thread.rs:108

**Comment by wez** [comment]
Interesting!  Try updating the addon and let me know what happens next!

**Comment by Leopoldpaul** [comment]
WOW it's working. Thanks what fast support and amazing work 🙌
