### ISSUE TITLE
Switching to Effects works... but cant switch back to single color...

### ISSUE THREAD

**Issue by superpunkduck** [wez/govee2mqtt#25]
I am able to set up an automation to Chose an effect... that works fine...
![image](https://github.com/wez/govee2mqtt/assets/50434137/7eeba1db-f8d0-4c03-926e-4ec7d5a18ad0)

But there doesnt seem to be a way to switch back to just a single color like warm white....
I tried the Light.TurnOn Service with a Kelvin Value...   It runs manuallly but will not work in an automation
![image](https://github.com/wez/govee2mqtt/assets/50434137/ff5d2a32-4c7d-4ca9-8364-8cdfcf4ead6c)

**Comment by wez** [comment]
What's in the addon logs?

**Comment by superpunkduck** [comment]
Nevermind.. i figured it out... color tempurature works... i think it was just failing in my home assistant because i had another script running at the same time with a repeating light: turn on service
