### ISSUE TITLE
Error after HAOS reboot

### ISSUE THREAD

**Issue by Explodedkola** [wez/govee2mqtt#255]
### Govee Device SKU

H6076

### Govee2MQTT Version

2024.07.13-82ddc6e9

### Describe the issue

Govee2mqtt has been working great for a long time now, but I just did a reboot and now none of my devices are available and the govee2mqtt addon keeps crashing. It starts up and gets to “querying platform api for device list” then I get an error as shown in the screenshot and then the addon shuts down. I have made no changes to the home assistant for weeks either. I didn’t install any updates, except for after it stopped working I updated this addon, but that did not fix the issue.
![IMG_3773](https://github.com/user-attachments/assets/ce0975b4-aa10-40e1-bdc0-90be7376525c)

### Startup Diagnostics

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
GOVEE_API_KEY=REDACTED
GOVEE_MQTT_HOST=core-mosquitto
GOVEE_TEMPERATURE_SCALE=C
GOVEE_EMAIL=REDACTED
GOVEE_PASSWORD=REDACTED
GOVEE_MQTT_PASSWORD=REDACTED
GOVEE_LAN_BROADCAST_ALL=false
GOVEE_MQTT_USER=addons
GOVEE_MQTT_PORT=1883
++ cd /app
++ exec /app/govee serve
[2024-07-30T19:35:26 INFO  govee::commands::serve] Starting service. version 2024.07.13-82ddc6e9
[2024-07-30T19:35:26 INFO  govee::commands::serve] Querying platform API for device list
[2024-07-30T19:36:26 WARN  govee::cache] error sending request for url (https://openapi.api.govee.com/router/api/v1/user/devices): operation timed out, will use prior results
Error: error sending request for url (https://openapi.api.govee.com/router/api/v1/user/devices): operation timed out

Stack backtrace:
   0: std::backtrace::Backtrace::create
   1: anyhow::error::<impl anyhow::Error>::msg
   2: anyhow::__private::format_err
   3: govee::cache::CacheResult<T>::into_result
   4: govee::platform_api::GoveeApiClient::get_devices::{{closure}}
   5: govee::commands::serve::ServeCommand::run::{{closure}}
   6: govee::Args::run::{{closure}}
   7: tokio::runtime::park::CachedParkThread::block_on
   8: tokio::runtime::context::runtime::enter_runtime
   9: tokio::runtime::runtime::Runtime::block_on
  10: govee::main
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: std::rt::lang_start::{{closure}}
  13: std::rt::lang_start_internal
  14: main
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by CamSoper** [comment]
You're experience the same thing as me, except I use the container.

Already logged an issue: #254
