### ISSUE TITLE
H5103 temperature sensor

### ISSUE THREAD

**Issue by ebiancarelli** [wez/govee2mqtt#27]
I have the 5103 temperature devices and the [5040/5054](https://us.govee.com/collections/smart-water-sensors/products/wireless-water-leak-detector) in my home. Both are Wifi connected.

Are you interested in adding other device types to this project? 

<img width="454" alt="image" src="https://github.com/wez/govee2mqtt/assets/156859/ac81ab46-b390-4718-91fa-82ed25608999">

**Comment by wez** [comment]
Yeah I'd like to see them added. I don't have those particular devices.
In general, testing a new device without having access to it is slow and frustrating.

I did just obtain a humidifier which notionally supports reading back the temperature and humidity, although Govee's API returns crap data for it.
I'll be looking at that more today and laying down the foundation for reporting device-associated-sensors.

That might happen to enable your device without any additional effort.

**Comment by ebiancarelli** [comment]
I've got the code and have been reading it. If you need me to test and debug I can do that.

**Comment by TeDeVPrime** [comment]
how about the space heaters?

**Comment by wez** [comment]
@ebiancarelli can you run and share the output from:

```console
$ docker run --rm ghcr.io/wez/govee2mqtt /app/govee http-control --api-key $GOVEE_API_KEY --id $DEVICE_ID info
```

```console
$ docker run --rm ghcr.io/wez/govee2mqtt /app/govee http-control --api-key $GOVEE_API_KEY --id $DEVICE_ID status
```

for each device? (`$DEVICE_ID` is the colon-separated-hex id for your device).

**Comment by wez** [comment]
if you already know how to build and run the code from the repo, you don't need docker:

```console
$ ./target/debug/govee http-control --api-key $GOVEE_API_KEY --id $DEVICE_ID info
```

**Comment by ebiancarelli** [comment]
Ok - I will try in a few hours when I'm home.

--
  Ernie Biancarelli
  ***@***.***

**Comment by ebiancarelli** [comment]
```
$ cargo run http-control --id C6:1A:D7:37:36:39:34:10 info
   Compiling govee v0.1.0 (/Users/dad/code/govee2mqtt)
    Finished dev [unoptimized + debuginfo] target(s) in 1.81s
     Running `target/debug/govee http-control --id 'C6:1A:D7:37:36:39:34:10' info`
Loading environment overrides from "/Users/dad/code/govee2mqtt/.env"
HttpDeviceInfo {
    sku: "H5103",
    device: "C6:1A:D7:37:36:39:34:10",
    device_name: "Outside Temp Guage",
    device_type: Thermometer,
    capabilities: [
        DeviceCapability {
            kind: Property,
            instance: "sensorTemperature",
            parameters: None,
            alarm_type: None,
            event_state: None,
        },
        DeviceCapability {
            kind: Property,
            instance: "sensorHumidity",
            parameters: None,
            alarm_type: None,
            event_state: None,
        },
    ],
}
$ cargo run http-control --id 33:F7:D7:37:36:39:40:12 info
   Compiling govee v0.1.0 (/Users/dad/code/govee2mqtt)
    Finished dev [unoptimized + debuginfo] target(s) in 2.25s
     Running `target/debug/govee http-control --id '33:F7:D7:37:36:39:40:12' info`
Loading environment overrides from "/Users/dad/code/govee2mqtt/.env"
HttpDeviceInfo {
    sku: "H5103",
    device: "33:F7:D7:37:36:39:40:12",
    device_name: "Inside Temp Guage",
    device_type: Thermometer,
    capabilities: [
        DeviceCapability {
            kind: Property,
            instance: "sensorTemperature",
            parameters: None,
            alarm_type: None,
            event_state: None,
        },
        DeviceCapability {
            kind: Property,
            instance: "sensorHumidity",
            parameters: None,
            alarm_type: None,
            event_state: None,
        },
    ],
}
```

**Comment by ebiancarelli** [comment]
**Status Command**
```
$ cargo run http-control --id C6:1A:D7:37:36:39:34:10 status
   Compiling govee v0.1.0 (/Users/dad/code/govee2mqtt)
    Finished dev [unoptimized + debuginfo] target(s) in 3.27s
     Running `target/debug/govee http-control --id 'C6:1A:D7:37:36:39:34:10' status`
Loading environment overrides from "/Users/dad/code/govee2mqtt/.env"
HttpDeviceState {
    sku: "H5103",
    device: "C6:1A:D7:37:36:39:34:10",
    capabilities: [
        DeviceCapabilityState {
            kind: Online,
            instance: "online",
            state: Object {
                "value": Bool(true),
            },
        },
        DeviceCapabilityState {
            kind: Property,
            instance: "sensorTemperature",
            state: Object {
                "value": Number(3030),
            },
        },
        DeviceCapabilityState {
            kind: Property,
            instance: "sensorHumidity",
            state: Object {
                "value": Object {
                    "currentHumidity": Number(5760),
                },
            },
        },
    ],
}
```

**Comment by ebiancarelli** [comment]
Turns out that the 5040 is [not returned from the API](https://developer.govee.com/discuss/659adf367dd461001b3014de)

**Comment by sdaltons1** [comment]
> Turns out that the 5040 is [not returned from the API](https://developer.govee.com/discuss/659adf367dd461001b3014de)

I actually had the 5040/5054 combo on order and it came today.  So I was working on setting it up and appreciate you already looking into this.  Hopefully it will get added to the API!

**Comment by wez** [comment]
@ebiancarelli thanks; do you happen to know what the corresponding humidity is that is reported in the app?  I suspect that the 5760 value needs to be scaled in some way.  If you can figure out the relationship, then we can report something reasonable for it to home assistant.

**Comment by wez** [comment]
Same for the temperature; does 3030 represent 30.3C, or 30.3F, or something else completely?

**Comment by ebiancarelli** [comment]
Temperature is in C, so 3030 = 30.3C
Humidity is in percent, so 5760 = 57.6%

**Comment by wez** [comment]
Thanks; it's possible that `2024.01.10-86c015b5` will populate some sensor entities for you; please give it a try and let me know!

**Comment by ebiancarelli** [comment]
Appears to work!

```
[2024-01-10T09:17:52 TRACE govee::service::state] updated state for Inside Temp Guage (33:F7:D7:37:36:39:40:12)
[2024-01-10T09:17:52 TRACE govee::service::hass] gv2mqtt/sensor/sensor-33F7D73736394012-sensortemperature/state -> 27.6
[2024-01-10T09:17:52 TRACE govee::service::hass] gv2mqtt/sensor/sensor-33F7D73736394012-sensorhumidity/state -> 72.5
[2024-01-10T09:17:52 INFO  govee::service::state] requesting update via Platform API Outside Temp Guage (C6:1A:D7:37:36:39:34:10) None
[2024-01-10T09:17:53 TRACE govee::service::state] updated state for Outside Temp Guage (C6:1A:D7:37:36:39:34:10)
[2024-01-10T09:17:53 TRACE govee::service::hass] gv2mqtt/sensor/sensor-C61AD73736393410-sensortemperature/state -> 27.5
[2024-01-10T09:17:53 TRACE govee::service::hass] gv2mqtt/sensor/sensor-C61AD73736393410-sensorhumidity/state -> 75.7
```
<img width="667" alt="image" src="https://github.com/wez/govee2mqtt/assets/156859/057af1b9-46d9-42dd-8ba7-484e584df4b0">

**Comment by ebiancarelli** [comment]
FYI -  **_Gauge_** is misspelled

**Comment by wez** [comment]
re: spelling, that name comes from what is entered in the Govee app for the device name!

**Comment by wez** [comment]
Ok, I think we can close this!
