### ISSUE TITLE
Add-On stops working with 2024.10.2

### ISSUE THREAD

**Issue by FRANKWHITE1** [wez/govee2mqtt#295]
### Govee Device SKU

... 

### Govee2MQTT Version

2024.07.13-82ddc6e9

### Describe the issue

Since updating Core to **2024.10.2** and Home Assistant Operating System to **Version: 13.2** the add-on inmediately shuts down after starting

### Startup Diagnostics

  13: main
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
GOVEE_API_KEY=REDACTED
GOVEE_MQTT_HOST=core-mosquitto
GOVEE_TEMPERATURE_SCALE=C
GOVEE_EMAIL=REDACTED
GOVEE_PASSWORD=REDACTED
GOVEE_MQTT_PASSWORD=REDACTED
GOVEE_MQTT_USER=addons
GOVEE_MQTT_PORT=1883
++ cd /app
++ exec /app/govee serve
[2024-10-17T19:13:09 INFO  govee::commands::serve] Starting service. version 2024.07.13-82ddc6e9
[2024-10-17T19:13:09 INFO  govee::commands::serve] Querying platform API for device list
Error: request https://openapi.api.govee.com/router/api/v1/user/devices status 401: Unauthorized. Response body: 

Stack backtrace:
   0: anyhow::error::<impl anyhow::Error>::msg
   1: anyhow::__private::format_err
   2: govee::cache::CacheResult<T>::into_result
   3: govee::platform_api::GoveeApiClient::get_devices::{{closure}}
   4: govee::commands::serve::ServeCommand::run::{{closure}}
   5: govee::Args::run::{{closure}}
   6: tokio::runtime::park::CachedParkThread::block_on
   7: tokio::runtime::context::runtime::enter_runtime
   8: tokio::runtime::runtime::Runtime::block_on
   9: govee::main
  10: std::sys_common::backtrace::__rust_begin_short_backtrace
  11: std::rt::lang_start::{{closure}}
  12: std::rt::lang_start_internal
  13: main
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
GOVEE_API_KEY=REDACTED
GOVEE_MQTT_HOST=core-mosquitto
GOVEE_TEMPERATURE_SCALE=C
GOVEE_EMAIL=REDACTED
GOVEE_PASSWORD=REDACTED
GOVEE_MQTT_PASSWORD=REDACTED
GOVEE_MQTT_USER=addons
GOVEE_MQTT_PORT=1883
++ cd /app
++ exec /app/govee serve
[2024-10-17T19:33:42 INFO  govee::commands::serve] Starting service. version 2024.07.13-82ddc6e9
[2024-10-17T19:33:42 INFO  govee::commands::serve] Querying platform API for device list
[2024-10-17T19:33:42 WARN  govee::cache] request https://openapi.api.govee.com/router/api/v1/user/devices status 401: Unauthorized. Response body: , will use prior results
Error: request https://openapi.api.govee.com/router/api/v1/user/devices status 401: Unauthorized. Response body: 

Stack backtrace:
   0: anyhow::error::<impl anyhow::Error>::msg
   1: anyhow::__private::format_err
   2: govee::cache::CacheResult<T>::into_result
   3: govee::platform_api::GoveeApiClient::get_devices::{{closure}}
   4: govee::commands::serve::ServeCommand::run::{{closure}}
   5: govee::Args::run::{{closure}}
   6: tokio::runtime::park::CachedParkThread::block_on
   7: tokio::runtime::context::runtime::enter_runtime
   8: tokio::runtime::runtime::Runtime::block_on
   9: govee::main
  10: std::sys_common::backtrace::__rust_begin_short_backtrace
  11: std::rt::lang_start::{{closure}}
  12: std::rt::lang_start_internal
  13: main
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

### Home Assistant Logs

Logger: homeassistant.components.hassio
Quelle: components/hassio/websocket_api.py:135
Integration: Home Assistant Supervisor ([Dokumentation](https://www.home-assistant.io/integrations/hassio), [Probleme](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+hassio%22))
Erstmals aufgetreten: 18:22:48 (4 Vorkommnisse)
Zuletzt protokolliert: 19:10:14

Failed to to call /addons/b9845f46_govee2mqtt/start - Another job is running for job group addon_b9845f46_govee2mqtt
Failed to to call /addons/b9845f46_govee2mqtt/stats - Container addon_b9845f46_govee2mqtt is not running

**Comment by neoalarrode** [comment]
Same here

**Comment by FRANKWHITE1** [comment]
Thanks for your reply wez. I reinstalled the add-on in HomeAssistant and setup it up again. Now it seems to work. Still have no clue why it suddenly stopped working despite no changes in my login credentials
