### ISSUE TITLE
DIY Scenes?

### ISSUE THREAD

**Issue by Tom-Sumner** [wez/govee2mqtt#3]
Looks good, well done!

Is there a way to use DIY Scenes?

**Comment by wez** [comment]
You should be able to once https://github.com/wez/govee2mqtt/actions/runs/7404007883 completes.
Once done, you can go to the addon and check for updates and install and restart the addon.

**Comment by wez** [comment]
This has now published.  DIY scenes now get listed along side the other scenes and show up in the Effects list on the device.

**Comment by wez** [comment]
Check for updates in the addons section again; you should see a newer version available now.

**Comment by Tom-Sumner** [comment]
@wez 

Ive had some problems setting this up as mqtt didn't auto fill in the details so I've done my best and used my login and the username and password for mqtt

Ive started your add on and I get this in the log

   7: govee::undoc_api::GoveeUndocumentedApi::login_account::{{closure}}
   8: govee::commands::serve::ServeCommand::run::{{closure}}
   9: govee::Args::run::{{closure}}
  10: tokio::runtime::park::CachedParkThread::block_on
  11: tokio::runtime::runtime::Runtime::block_on
  12: govee::main
  13: std::sys_common::backtrace::__rust_begin_short_backtrace
  14: std::rt::lang_start::{{closure}}
  15: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:284:13
  16: std::panicking::try::do_call
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40
  17: std::panicking::try
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19
  18: std::panic::catch_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14
  19: std::rt::lang_start_internal::{{closure}}
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:148:48
  20: std::panicking::try::do_call
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40
  21: std::panicking::try
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19
  22: std::panic::catch_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14
  23: std::rt::lang_start_internal
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:148:20
  24: std::rt::lang_start
  25: main
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by wez** [comment]
> device becomes unavailable every now and then

All the devices setup by this addon are always available. If you're seeing things go unavailable it suggests that the mqtt connection is dropping out.

I'd love to see the logs to see if there is more context on what is happening there.

**Comment by wez** [comment]
Have you set a timeout in your mqtt broker configuration? If so what is it set to?
govee2mqtt will send keepalives to the broker every 10 seconds.

**Comment by Tom-Sumner** [comment]
@wez 
I dont think so. i cant see a option in the config of it

**Comment by wez** [comment]
> i changed the time to 40 seconds

what setting did you change?

> does the new api docs support music modes and snapshots?

Music modes show up in the list of Effects for a light.
I don't really use the govee app, so I'm not sure what you mean by snapshots. If you mean the "One click" stuff, you can those in home assistant as Scenes.

If you mean something else, can you tell me more about what it is and how you set them up?

**Comment by Tom-Sumner** [comment]
@wez 
that makes sense. you are correct in the snapshots being the one click things. to fix it seemingly i deleted the mqtt devices and then set one up again using the broker details and then clicked show advanced then next and set the field called timeout or refresh time. i cant remember to 40. have not tried with lower or higher apart from 60 where i was experiencing issues.

**Comment by wez** [comment]
OK, well, as part of looking into this, I've made some adjustments to improve how things are handled if we get disconnected.
