### ISSUE TITLE
Not finding MQTT Broker (Docker)

### ISSUE THREAD

**Issue by godfa7h3r** [wez/govee2mqtt#310]
Hello!

Been trying for weeks to get this working and I'm at a loss. Home Assistant, mosquitto MQTT, and govee2mqtt are all setup on Docker containers. 

I have the mosquitto MQTT broker successfully integrated into HA. I've tested functionality by publishing data from the MQTT integration page of HA and using MQTT Explorer to monitor. So I know that it's configured and functioning correctly. 

The MQTT Integration page of HA shows an IP address of 192.168.86.21

In my govee2mqtt env I have the following setup as the MQTT host: 
`GOVEE_MQTT_HOST=192.168.86.21`

Checking the Docker logs of the govee2mqtt container, I can see that it's running and is finding my account and devices just fine. But there is this error in the logs which is what is preventing the final step of getting it to talk to the MQTT Broker in HA. 

`Error: Please specify the mqtt broker either via the --mqtt-host parameter or by setting $GOVEE_MQTT_HOST`

Any help here would be greatly appreciated as this one of the last pieces of my HA puzzle!

Thank you!

**Comment by Phillycityboy** [comment]
Unsubscribe

Sent from AOL on Android 
 
  On Fri, Nov 22, 2024 at 7:10 PM, ***@***.***> wrote:   


Hello!

Been trying for weeks to get this working and I'm at a loss. Home Assistant, mosquitto MQTT, and govee2mqtt are all setup on Docker containers.

I have the mosquitto MQTT broker successfully integrated into HA. I've tested functionality by publishing data from the MQTT integration page of HA and using MQTT Explorer to monitor. So I know that it's configured and functioning correctly.

The MQTT Integration page of HA shows an IP address of 192.168.86.21

In my govee2mqtt env I have the following setup as the MQTT host:
GOVEE_MQTT_HOST=192.168.86.21

Checking the Docker logs of the govee2mqtt container, I can see that it's running and is finding my account and devices just fine. But there is this error in the logs which is what is preventing the final step of getting it to talk to the MQTT Broker in HA.

Error: Please specify the mqtt broker either via the --mqtt-host parameter or by setting $GOVEE_MQTT_HOST

Any help here would be greatly appreciated as this one of the last pieces of my HA puzzle!

Thank you!

**Comment by JanSucco** [comment]
I had the same error. Do you use Portainer? Then you need to specify **stack.env**.

![Screenshot 2024-12-16 152817](https://github.com/user-attachments/assets/f6f4ac4a-902f-4cdd-8b94-3027838936cd)

Now it works for me.

**Comment by wez** [comment]
When running the addon in HASS, together with the MQTT addon, leave the MQTT information in govee2mqtt blank and HASS will automatically provide the correct information.
