### ISSUE TITLE
Tap-to-Run & Snapshots not showing in HA

### ISSUE THREAD

**Issue by miketunes** [wez/govee2mqtt#315]
### Govee Device SKU

H606A

### Govee2MQTT Version

2024.07.13-82ddc6e9

### Describe the issue

I'm following the FAQ to enable video effects, but they don't appear in HA after purging cache.  I do see an old shortcut I had since removed - so it was working, it just doesn't seem to add new effects.  

### Startup Diagnostics

not sure where to generate from HAos

**Comment by thibaud-sanchez** [comment]
Maybe related to : https://github.com/wez/govee2mqtt/issues/317

**Comment by miketunes** [comment]
Deleted my dreamview and purged cache - still now scenes or new effects in HA

**Comment by thibaud-sanchez** [comment]
Did you try to Restart addon and reload mqtt config?

**Comment by miketunes** [comment]
Ah thanks, that was it.

**Comment by thibaud-sanchez** [comment]
Reboot or action blocking others ?

**Comment by miketunes** [comment]
I did an OS reboot and that brought the updated effects in
