### ISSUE TITLE
H7102 Smart Tower Fan

### ISSUE THREAD

**Issue by wwelles** [wez/govee2mqtt#33]
Thanks for the great work here!

I was able to get an API key and setup via docker. My device was recognized however the controls are unavailable. I'm guessing this is because your library does not currently support fans or my fan specifically.

Happy to provide whatever needed to get this model to work. I'm a software developer intimately familiar with REST APIs, just don't know Rust :\

Logs:
> [2024-01-08T06:29:23 INFO  govee::commands::serve] Starting service. version 2024.01.07-ac926c47
[2024-01-08T06:29:23 INFO  govee::commands::serve] Querying platform API for device list
[2024-01-08T06:29:24 INFO  govee::commands::serve] Querying undocumented API for device + room list
[2024-01-08T06:29:25 INFO  govee::service::iot] Connected to IoT: CONNACK code 0: Connection Accepted.
[2024-01-08T06:29:25 INFO  govee::commands::serve] Starting LAN discovery
[2024-01-08T06:29:25 INFO  govee::service::iot] IoT (re)connected with status CONNACK code 0: Connection Accepted.
[2024-01-08T06:29:29 INFO  govee::commands::serve] Devices returned from Govee's APIs
[2024-01-08T06:29:29 INFO  govee::commands::serve] Master Thermometer (7E:BD:18:1F:6C:F3:38:44) sku=H5179
[2024-01-08T06:29:29 INFO  govee::commands::serve]   Platform API: devices.types.thermometer. supports_rgb=false supports_brightness=false
[2024-01-08T06:29:29 INFO  govee::commands::serve]                 color_temp=None segment_rgb=None
[2024-01-08T06:29:29 INFO  govee::commands::serve]   Undoc: room=None supports_iot=false ble_only=true
[2024-01-08T06:29:29 INFO  govee::commands::serve]
[2024-01-08T06:29:29 INFO  govee::commands::serve] Upper Stairs (48:1A:A4:C1:38:87:7D:5E) sku=H6110
[2024-01-08T06:29:29 INFO  govee::commands::serve]   Platform API: devices.types.light. supports_rgb=false supports_brightness=false
[2024-01-08T06:29:29 INFO  govee::commands::serve]                 color_temp=None segment_rgb=None
[2024-01-08T06:29:29 INFO  govee::commands::serve]   Undoc: room=None supports_iot=true ble_only=false
[2024-01-08T06:29:29 INFO  govee::commands::serve]
[2024-01-08T06:29:29 INFO  govee::commands::serve] Smart Tower Fan (13:62:D4:AD:FC:BB:44:DE) sku=H7102
[2024-01-08T06:29:29 INFO  govee::commands::serve]   Platform API: devices.types.fan. supports_rgb=false supports_brightness=false
[2024-01-08T06:29:29 INFO  govee::commands::serve]                 color_temp=None segment_rgb=None
[2024-01-08T06:29:29 INFO  govee::commands::serve]   Undoc: room=None supports_iot=true ble_only=false
[2024-01-08T06:29:29 INFO  govee::commands::serve]
[2024-01-08T06:29:29 INFO  govee::service::http] http server addr is 0.0.0.0:8056
[2024-01-08T06:29:35 INFO  govee::service::hass] MQTT connected with status=CONNACK code 0: Connection Accepted.
[2024-01-08T06:29:49 INFO  govee::commands::serve] requesting update via IoT MQTT Upper Stairs (48:1A:A4:C1:38:87:7D:5E) None
[2024-01-08T06:29:49 INFO  govee::commands::serve] requesting update via IoT MQTT Smart Tower Fan (13:62:D4:AD:FC:BB:44:DE) None
[2024-01-08T06:30:10 INFO  govee::service::hass] Home Assistant status changed: online
[2024-01-08T06:34:34 ERROR govee::service::iot] Decoding IoT Packet: govee::service::iot::start_iot_client::{{closure}}::{{closure}}::Packet missing field `state` at line 1 column 179. Input: {"proType":0,"msg":"{\"transaction\":\"u_1704720875251\",\"sku\":\"H6110\",\"device\":\"48:1A:A4:C1:38:87:7D:5E\",\"cmdVersion\":0,\"type\":0,\"cmd\":\"online\",\"data\":\"{}\"}"} {"proType":0,"msg":"{\"transaction\":\"u_1704720875251\",\"sku\":\"H6110\",\"device\":\"48:1A:A4:C1:38:87:7D:5E\",\"cmdVersion\":0,\"type\":0,\"cmd\":\"online\",\"data\":\"{}\"}"}

Device:
![image](https://github.com/wez/govee2mqtt/assets/5238131/e24bc093-83b6-4721-afbb-c5627b4331fd)

**Comment by wez** [comment]
Please share the output from:

```console
$ docker run --rm ghcr.io/wez/govee2mqtt /app/govee http-control --api-key $GOVEE_API_KEY --id 13:62:D4:AD:FC:BB:44:DE info
```

```console
$ docker run --rm ghcr.io/wez/govee2mqtt /app/govee http-control --api-key $GOVEE_API_KEY --id 13:62:D4:AD:FC:BB:44:DE status
```

**Comment by wwelles** [comment]
Info:

```
HttpDeviceInfo {
    sku: "H7102",
    device: "13:62:D4:AD:FC:BB:44:DE",
    device_name: "Smart Tower Fan",
    device_type: Fan,
    capabilities: [
        DeviceCapability {
            kind: OnOff,
            instance: "powerSwitch",
            parameters: Some(
                Enum {
                    options: [
                        EnumOption {
                            name: "on",
                            value: Number(1),
                            extras: {},
                        },
                        EnumOption {
                            name: "off",
                            value: Number(0),
                            extras: {},
                        },
                    ],
                },
            ),
            alarm_type: None,
            event_state: None,
        },
        DeviceCapability {
            kind: Toggle,
            instance: "oscillationToggle",
            parameters: Some(
                Enum {
                    options: [
                        EnumOption {
                            name: "on",
                            value: Number(1),
                            extras: {},
                        },
                        EnumOption {
                            name: "off",
                            value: Number(0),
                            extras: {},
                        },
                    ],
                },
            ),
            alarm_type: None,
            event_state: None,
        },
        DeviceCapability {
            kind: WorkMode,
            instance: "workMode",
            parameters: Some(
                Struct {
                    fields: [
                        StructField {
                            field_name: "workMode",
                            field_type: Enum {
                                options: [
                                    EnumOption {
                                        name: "Normal",
                                        value: Number(1),
                                        extras: {},
                                    },
                                    EnumOption {
                                        name: "Custom",
                                        value: Number(2),
                                        extras: {},
                                    },
                                    EnumOption {
                                        name: "Auto",
                                        value: Number(3),
                                        extras: {},
                                    },
                                    EnumOption {
                                        name: "Sleep",
                                        value: Number(5),
                                        extras: {},
                                    },
                                    EnumOption {
                                        name: "Nature",
                                        value: Number(6),
                                        extras: {},
                                    },
                                ],
                            },
                            default_value: None,
                            required: true,
                        },
                        StructField {
                            field_name: "modeValue",
                            field_type: Enum {
                                options: [
                                    EnumOption {
                                        name: "Normal",
                                        value: Null,
                                        extras: {
                                            "options": Array [
                                                Object {
                                                    "value": Number(1),
                                                },
                                                Object {
                                                    "value": Number(2),
                                                },
                                                Object {
                                                    "value": Number(3),
                                                },
                                                Object {
                                                    "value": Number(4),
                                                },
                                                Object {
                                                    "value": Number(5),
                                                },
                                                Object {
                                                    "value": Number(6),
                                                },
                                                Object {
                                                    "value": Number(7),
                                                },
                                                Object {
                                                    "value": Number(8),
                                                },
                                            ],
                                        },
                                    },
                                    EnumOption {
                                        name: "Custom",
                                        value: Null,
                                        extras: {
                                            "defaultValue": Number(0),
                                        },
                                    },
                                    EnumOption {
                                        name: "Auto",
                                        value: Null,
                                        extras: {
                                            "defaultValue": Number(0),
                                        },
                                    },
                                    EnumOption {
                                        name: "Sleep",
                                        value: Null,
                                        extras: {
                                            "defaultValue": Number(0),
                                        },
                                    },
                                    EnumOption {
                                        name: "Nature",
                                        value: Null,
                                        extras: {
                                            "defaultValue": Number(0),
                                        },
                                    },
                                ],
                            },
                            default_value: None,
                            required: true,
                        },
                    ],
                },
            ),
            alarm_type: None,
            event_state: None,
        },
    ],
}
```

Status:
```
HttpDeviceState {
    sku: "H7102",
    device: "13:62:D4:AD:FC:BB:44:DE",
    capabilities: [
        DeviceCapabilityState {
            kind: Online,
            instance: "online",
            state: Object {
                "value": Bool(true),
            },
        },
        DeviceCapabilityState {
            kind: OnOff,
            instance: "powerSwitch",
            state: Object {
                "value": Number(0),
            },
        },
        DeviceCapabilityState {
            kind: Toggle,
            instance: "oscillationToggle",
            state: Object {
                "value": Number(1),
            },
        },
        DeviceCapabilityState {
            kind: WorkMode,
            instance: "workMode",
            state: Object {
                "value": Object {
                    "modeValue": Number(1),
                    "workMode": Number(3),
                },
            },
        },
    ],
}
```

**Comment by wez** [comment]
Thanks; the metadata looks similar to that of a humidifier and I'm currently working through supporting that.
I'll review once that's done; the tricky part in this is mapping the metadata to the hass entities without too many assumptions.

**Comment by wwelles** [comment]
Great, thanks for the quick response and work for the community!

Happy to help further if there's something I can do.

**Comment by wez** [comment]
The challenge here is that workMode is a bit kooky.  It represents a mode with five states, where each mode state has a corresponding parameter value.  One of the modes (Normal) has defined inputs, but the others are unspecified.

There's no metadata to describe these values, and no documentation to describe what the metadata actually means.
The Govee docs are on the surface good, but when you dig deeper, there's so much that is undefined or unspecified.

For my humidifer, in auto mode, the mode parameter value controls the target humidity. The input range for that is not specified at all in the metadata, and I'm having to reverse engineer it by packet sniffing.
It's not good.

In terms of mapping this into hass, the auto/target humidity maps into the hass humidifier entity, but the other values do not. They need to have separate input entities of the appropriate type created for them.

I suspect that a similar situation will apply to the fan.

The simplest case for exposing this stuff is to ignore the native home assistant entity types and just export select and number entities; that's probably what I'll do once I'm done working through this.

Then a second pass can be to figure out how to smoosh it into the fan entity.

**Comment by wwelles** [comment]
I see, thanks for extrapolating a bit. I'm really just looking for the ability to turn it on and off as I have a temperature sensor near it that would allow me to simulate the auto mode built into the app with an HA automation. 

Obviously a complete mapping of functionality is better, but IMHO partial (if possible) would be better than the nothing sandwich it currently is for my model. Sounds like this might be your plan with the select and number entities prior to a second fan entity.

For a proper fan entity, I could probably do some packet sniffing here if given some guidance on filters, etc. I've used Wireshark in the past to sniff traffic.

Let me know your thoughts. Really appreciate your work here.

**Comment by wwelles** [comment]
Thanks @wez.

I just followed your instructions and I'm able to turn the fan on and off correctly now!

Here's how it reports in HA:
![image](https://github.com/wez/govee2mqtt/assets/5238131/8465df15-f095-455f-9f45-9d4d299d32c3)

**Comment by wez** [comment]
The `Normal` mode parameter stuff is missing from the UI; did HASS log anything about it?  There should be a number entity being registered for it to let you set that level.

**Comment by wwelles** [comment]
No entity for that:
![image](https://github.com/wez/govee2mqtt/assets/5238131/db493fb5-37c9-49b9-b7e7-8590562874f3)

Didn't see anything off in HA logs.

**Comment by sdaltons1** [comment]
Not trying to overstep here. Just adding context for H7111 fan.

The "parameters" in the pic showed up after Wez made changes for the humidifier. 

Auto, custom, fanspeed (speed options: 1-8), nature, sleep, and storm (storm is called turbo in govee app) are the available modes. 

![IMG_0432](https://github.com/wez/govee2mqtt/assets/93367436/48899b15-4a3e-4990-8af8-6bef9b88a60a)

**Comment by wez** [comment]
OK, so it looks like the parameter values aren't being populated. Would be good to get the output from this, and then try changing the mode/parameters in the Govee app and trying it again to see whether and how the data changes:

```
$ docker run --rm ghcr.io/wez/govee2mqtt /app/govee http-control --api-key $GOVEE_API_KEY --id 13:62:D4:AD:FC:BB:44:DE status
```

(but replace that id with the id for your device)

so that we can see if they are being reported reasonably by the platform API.

For my humidifier, I had to essentially ignore the state data from the Platform API; while the metadata is useful for figuring out what to call the entities, I had to parse packets from the IoT API to determine the values.

**Comment by sdaltons1** [comment]
Ok here we go. The only option available for me to run these commands wouldn't let me copy so screenshots it is. 

First 3 are fan off, sleep mode, nature mode

![fan off](https://github.com/wez/govee2mqtt/assets/93367436/7cdee8b2-9346-4d2f-b2b1-4b711908744f)

![fan sleep](https://github.com/wez/govee2mqtt/assets/93367436/3cf677d3-5404-4832-a49a-19ffa11264aa)

![fan turbo (aka storm)](https://github.com/wez/govee2mqtt/assets/93367436/a89aac90-d13f-4e97-a308-05bbb3204167)

**Comment by sdaltons1** [comment]
Then we have 

Nature mode, custom mode, normal speed 8

![fan nature](https://github.com/wez/govee2mqtt/assets/93367436/25d82228-1312-4ce4-a8b5-8f4ef3bb1ad9)

![fan custom](https://github.com/wez/govee2mqtt/assets/93367436/ef4d4171-f4c7-4ccd-b29c-bb55ae5525b2)

![fan normal, speed 8](https://github.com/wez/govee2mqtt/assets/93367436/7389f1b2-4a9d-4aa3-bf76-729343015ae9)

**Comment by wez** [comment]
In the latest addon update, I've made a change that will make a point of polling the state from the platform API for devices where we don't know for sure how to interpret the data from the IoT API.  That might make these devices start to do something more useful.

What I'd appreciate, if/when you have the time, is mapping the values from the app to the values you see in the state.

For example, for my humidifier, the target humidity value is encoded as `128 + percentage`, and since the device has a min humidity value of 40 that means that `168` is the smallest value for that particular mode.
I don't know if any of the parameters for fans are quite the same, but perhaps there are more meaningful labels for the options/modes in the app than are reported in the app metadata?

It would be great also to capture the IoT packets that go along with the modes; you can see those by running the debug level set to `govee::service::iot=debug,info`.

**Comment by sdaltons1** [comment]
fan is off

`[2024-01-10T09:41:39 DEBUG govee::service::iot] Packet { sku: Some("H7111"), device: Some("12:A8:D4:AD:FC:43:1F:A8"), cmd: Some("status"), msg: None, state: StateUpdate { on_off: Some(0), brightness: None, color: None, color_temperature_kelvin: None, sku: None, device: None }, op: Some(OpData { command: [Generic([AA, 12, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, B8]), NotifyHumidifierTimer { on: false }, NotifyHumidifierManualMode { param: 4 }, Generic([AA, 05, 02, 00, 08, 00, 3C, 00, 3C, 05, 00, 3C, 00, 3C, 01, FF, FF, FF, FF, A1]), Generic([AA, 05, 03, 05, 0A, 3C, 08, 0B, 86, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 1A]), NotifyHumidifierMode { mode: 5, param: 0 }, Generic([AA, 08, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, A2]), Generic([AA, 1F, 01, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, B5]), Generic([AA, 16, 00, FF, FF, FF, FF, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, BC])], mode_value: [], sleep_value: [], wakeup_value: [], timer_value: [] }) }
[2024-01-10T09:41:39 WARN  govee::hass_mqtt::switch] CapabilitySwitch::notify_state: Do something with DeviceCapabilityState {
    kind: Toggle,
    instance: "oscillationToggle",
    state: Object {
        "value": Number(0),
    },
}`

sleep mode

`[2024-01-10T09:42:06 DEBUG govee::service::iot] Packet { sku: Some("H7111"), device: Some("12:A8:D4:AD:FC:43:1F:A8"), cmd: Some("status"), msg: None, state: StateUpdate { on_off: Some(1), brightness: None, color: None, color_temperature_kelvin: None, sku: None, device: None }, op: Some(OpData { command: [Generic([AA, 12, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, B8]), NotifyHumidifierTimer { on: false }, NotifyHumidifierManualMode { param: 4 }, Generic([AA, 05, 02, 00, 08, 00, 3C, 00, 3C, 05, 00, 3C, 00, 3C, 01, FF, FF, FF, FF, A1]), Generic([AA, 05, 03, 05, 0A, 3C, 08, 0B, 86, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 1A]), NotifyHumidifierMode { mode: 5, param: 0 }, Generic([AA, 08, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, A2]), Generic([AA, 1F, 01, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, B5]), Generic([AA, 16, 00, FF, FF, FF, FF, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, BC])], mode_value: [], sleep_value: [], wakeup_value: [], timer_value: [] }) }
[2024-01-10T09:42:06 WARN  govee::hass_mqtt::switch] CapabilitySwitch::notify_state: Do something with DeviceCapabilityState {
    kind: Toggle,
    instance: "oscillationToggle",
    state: Object {
        "value": Number(0),
    },
}`

nature mode

`[2024-01-10T09:42:45 DEBUG govee::service::iot] Packet { sku: Some("H7111"), device: Some("12:A8:D4:AD:FC:43:1F:A8"), cmd: Some("ptReal"), msg: None, state: StateUpdate { on_off: None, brightness: None, color: None, color_temperature_kelvin: None, sku: None, device: None }, op: Some(OpData { command: [Generic([AA, 05, 06, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, A9]), NotifyHumidifierMode { mode: 6, param: 0 }], mode_value: [], sleep_value: [], wakeup_value: [], timer_value: [] }) }
[2024-01-10T09:42:45 WARN  govee::hass_mqtt::switch] CapabilitySwitch::notify_state: Do something with DeviceCapabilityState {
    kind: Toggle,
    instance: "oscillationToggle",
    state: Object {
        "value": Number(0),
    },
}`

turbo mode

`[2024-01-10T09:43:37 DEBUG govee::service::iot] Packet { sku: Some("H7111"), device: Some("12:A8:D4:AD:FC:43:1F:A8"), cmd: Some("ptReal"), msg: None, state: StateUpdate { on_off: None, brightness: None, color: None, color_temperature_kelvin: None, sku: None, device: None }, op: Some(OpData { command: [Generic([AA, 05, 07, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, A8]), NotifyHumidifierMode { mode: 7, param: 0 }, Generic([AA, 1F, 01, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, B5])], mode_value: [], sleep_value: [], wakeup_value: [], timer_value: [] }) }
[2024-01-10T09:43:37 WARN  govee::hass_mqtt::switch] CapabilitySwitch::notify_state: Do something with DeviceCapabilityState {
    kind: Toggle,
    instance: "oscillationToggle",
    state: Object {
        "value": Number(0),
    },
}`

normal, speed 8

`[2024-01-10T09:44:12 DEBUG govee::service::iot] Packet { sku: Some("H7111"), device: Some("12:A8:D4:AD:FC:43:1F:A8"), cmd: Some("ptReal"), msg: None, state: StateUpdate { on_off: None, brightness: None, color: None, color_temperature_kelvin: None, sku: None, device: None }, op: Some(OpData { command: [NotifyHumidifierManualMode { param: 8 }, NotifyHumidifierMode { mode: 1, param: 0 }], mode_value: [], sleep_value: [], wakeup_value: [], timer_value: [] }) }
[2024-01-10T09:44:12 WARN  govee::hass_mqtt::switch] CapabilitySwitch::notify_state: Do something with DeviceCapabilityState {
    kind: Toggle,
    instance: "oscillationToggle",
    state: Object {
        "value": Number(0),
    },
}`

normal, speed 1

`[2024-01-10T09:44:58 DEBUG govee::service::iot] Packet { sku: Some("H7111"), device: Some("12:A8:D4:AD:FC:43:1F:A8"), cmd: Some("ptReal"), msg: None, state: StateUpdate { on_off: None, brightness: None, color: None, color_temperature_kelvin: None, sku: None, device: None }, op: Some(OpData { command: [NotifyHumidifierManualMode { param: 1 }, NotifyHumidifierMode { mode: 1, param: 0 }], mode_value: [], sleep_value: [], wakeup_value: [], timer_value: [] }) }
[2024-01-10T09:44:58 WARN  govee::hass_mqtt::switch] CapabilitySwitch::notify_state: Do something with DeviceCapabilityState {
    kind: Toggle,
    instance: "oscillationToggle",
    state: Object {
        "value": Number(0),
    },
}`

**Comment by sdaltons1** [comment]
Let me know if you need anything else for the fans. 

Next up for me will be the purifier and a question about the H5082 dual plug, which is only giving a master on/off switch that toggles both sides of the plug together. The actual device allows independent control of each side.

**Comment by wez** [comment]
@sdaltons1 please open a separate issue for each device so that it is easier for me to keep track of things

**Comment by sdaltons1** [comment]
Hi Wez. The new request platform API state thing is awesome. 

Here's what it pulls for the h7111 fan. I guess at this point I'm just wondering if it would be possible to have the modes display on the main device screen, like you did for the humidifier. That or a speed slider would also be good. If not, no worries. 

`{
  "meta": {
    "capabilities": [
      {
        "alarmType": null,
        "eventState": null,
        "instance": "powerSwitch",
        "parameters": {
          "dataType": "ENUM",
          "options": [
            {
              "name": "on",
              "value": 1
            },
            {
              "name": "off",
              "value": 0
            }
          ]
        },
        "type": "devices.capabilities.on_off"
      },
      {
        "alarmType": null,
        "eventState": null,
        "instance": "oscillationToggle",
        "parameters": {
          "dataType": "ENUM",
          "options": [
            {
              "name": "on",
              "value": 1
            },
            {
              "name": "off",
              "value": 0
            }
          ]
        },
        "type": "devices.capabilities.toggle"
      },
      {
        "alarmType": null,
        "eventState": null,
        "instance": "workMode",
        "parameters": {
          "dataType": "STRUCT",
          "fields": [
            {
              "dataType": "ENUM",
              "defaultValue": null,
              "fieldName": "workMode",
              "options": [
                {
                  "name": "FanSpeed",
                  "value": 1
                },
                {
                  "name": "Custom",
                  "value": 2
                },
                {
                  "name": "Auto",
                  "value": 3
                },
                {
                  "name": "Sleep",
                  "value": 5
                },
                {
                  "name": "Nature",
                  "value": 6
                },
                {
                  "name": "Storm",
                  "value": 7
                }
              ],
              "required": true
            },
            {
              "dataType": "ENUM",
              "defaultValue": null,
              "fieldName": "modeValue",
              "options": [
                {
                  "name": "FanSpeed",
                  "options": [
                    {
                      "value": 1
                    },
                    {
                      "value": 2
                    },
                    {
                      "value": 3
                    },
                    {
                      "value": 4
                    },
                    {
                      "value": 5
                    },
                    {
                      "value": 6
                    },
                    {
                      "value": 7
                    },
                    {
                      "value": 8
                    }
                  ],
                  "value": null
                },
                {
                  "defaultValue": 0,
                  "name": "Custom",
                  "value": null
                },
                {
                  "defaultValue": 0,
                  "name": "Auto",
                  "value": null
                },
                {
                  "defaultValue": 0,
                  "name": "Sleep",
                  "value": null
                },
                {
                  "defaultValue": 0,
                  "name": "Nature",
                  "value": null
                },
                {
                  "defaultValue": 0,
                  "name": "Storm",
                  "value": null
                }
              ],
              "required": true
            }
          ]
        },
        "type": "devices.capabilities.work_mode"
      }
    ],
    "device": "12:A8:D4:AD:FC:43:1F:A8",
    "deviceName": "Smart Floor Fan",
    "sku": "H7111",
    "type": "devices.types.fan"
  },
  "state": {
    "capabilities": [
      {
        "instance": "online",
        "state": {
          "value": true
        },
        "type": "devices.capabilities.online"
      },
      {
        "instance": "powerSwitch",
        "state": {
          "value": 0
        },
        "type": "devices.capabilities.on_off"
      },
      {
        "instance": "oscillationToggle",
        "state": {
          "value": 0
        },
        "type": "devices.capabilities.toggle"
      },
      {
        "instance": "workMode",
        "state": {
          "value": {
            "modeValue": 8,
            "workMode": 6
          }
        },
        "type": "devices.capabilities.work_mode"
      }
    ],
    "device": "12:A8:D4:AD:FC:43:1F:A8",
    "sku": "H7111"
  }
}`

**Comment by wez** [comment]
@wwelles I'd love for you to try the latest version and let me know how it is working for you

**Comment by wwelles** [comment]
Assuming I'm using the correct build (`latest` docker container at time of writing), here's what I get:

![image](https://github.com/wez/govee2mqtt/assets/5238131/6d6ff514-7fda-4635-9515-9922f663994d)

Both the power switch and the oscillation work correctly, but nothing regarding the fan levels. Not sure if you were expecting anything there though.

**Comment by wez** [comment]
I don't think you're on the latest bits, run this to be sure: `docker compose up -d --pull=always`

**Comment by wwelles** [comment]
Ah you're right, I ran a similar command to get the latest container, here's what I have now:

![image](https://github.com/wez/govee2mqtt/assets/5238131/7e2965fd-e833-478b-b64f-72c55082ba53)

Most everything works as you'd expect. One minor exception would be the `Activate Normal Preset` 1 through 8 buttons control the fan speed.

**Comment by wez** [comment]
Those Normal preset buttons should be fixed in the latest version. I recommend deleting the device and restarting govee2mqtt to clear them out.

**Comment by wwelles** [comment]
Yep, that did the trick, thank you!

**Comment by wez** [comment]
Great, then I think we can close this!

**Comment by deonte1threatt** [comment]
Hey @wez,

I saw this was closed today and I can create a new issue if needed, but is it possible to have this as a fan entity where speed control is possible?

**Comment by wez** [comment]
please file a new issue!
