### ISSUE TITLE
all segments off but one

### ISSUE THREAD

**Issue by michalk-k** [wez/govee2mqtt#342]
### Govee Device SKU

H6076

### Govee2MQTT Version

2024.07.13-82ddc6e9

### Describe the issue

I have read FAQ and I know that there are problems controlling each segment separately. 
The Govee mobile app allows however to turn off all segments, leaving only one enabled.

I really need to be able to turn such a light as a night ambience.

Is there any workaround you could advice to achieve that? 
I thought making a scene could be a way, but somehow I found no such option. Maybe I missed something. I assume you are experienced with Govee products.

thank you in advance.

### Startup Diagnostics

N/A

**Comment by wez** [comment]
Sorry, the Govee API is the only known way to control segments, and it isn't very good for that.
