### ISSUE TITLE
Latest update breaks sliders

### ISSUE THREAD

**Issue by drbroccoli** [wez/govee2mqtt#348]
### Govee Device SKU

ALL

### Govee2MQTT Version

2024.12.30-5de5b504

### Describe the issue

Updated to the latest version pushed on 12/30, upon installation and a restart no slider controls work correctly with any Govee light. The sliders always show 0% no matter the intensity. Sliding and releasing will set the new intensity on the light but visually slider will go back to 0.

### Startup Diagnostics

Restarted HAOS (RPi4)

**Comment by marc3k18** [comment]
Same problem. Brightness is not updating properly.

**Comment by wez** [comment]
Fixed in the most recent update, thanks for reporting this!

**Comment by drbroccoli** [comment]
> Fixed in the most recent update, thanks for reporting this!

Woo! Thanks for the fast fix
