### ISSUE TITLE
"Effects" not present unless auth/api are provided

### ISSUE THREAD

**Issue by AlgoClaw** [wez/govee2mqtt#349]
### Govee Device SKU

H61A8

### Govee2MQTT Version

2024.12.30-c0545a87

### Describe the issue

If I start the docker container with the environment variables "GOVEE_EMAIL", "GOVEE_PASSWORD", and "GOVEE_API_KEY", the "Effects" UI element is present in HA.

However, if I exclude those variables when spinning up the container, the "Effects" button is not present.

### Startup Diagnostics

.

**Comment by wez** [comment]
I added a fallback for this case in the latest build; how's that work for you?

**Comment by AlgoClaw** [comment]
That worked. Thank you.
