### ISSUE TITLE
H6176 effect change turns strip ON but state stays OFF

### ISSUE THREAD

**Issue by Chavife** [wez/govee2mqtt#41]
Using H6176 outdoor 30m RGBIC 36V strip ligts
----------------
works:
```
{
    "state": "ON"
}
```
![image](https://github.com/wez/govee2mqtt/assets/18663896/63d535df-0e07-4336-b39b-8f6520c009fc)
----------------
Works (the light turns on and the effect is changed), but state does not update to ON
```
{
    "state": "ON",
    "effect": "Atlantis"
}
```
![image](https://github.com/wez/govee2mqtt/assets/18663896/8eab36c3-b184-4483-ad01-9c9636b7b52d)
----------------
the light after the command publishes OFF state (sequence bottom->up) and light is ON
![image](https://github.com/wez/govee2mqtt/assets/18663896/9aa8258d-d7f0-4cbf-8e27-49688ae91b48)

Issue: the state is inconsistent with the real state of the strip

**Comment by wez** [comment]
I've added a FAQ that answers this: https://github.com/wez/govee2mqtt/blob/main/docs/FAQ.md

**Comment by Chavife** [comment]
I can't see the answer for this in the FAQ. The mere issue is that the light strip is lit up and the state is showing OFF.

**Comment by wez** [comment]
Sorry, I misread this as being related to segments like your other issues. Please open a new issue with the information requested by the issue template and we can dig a bit deeper.
