### ISSUE TITLE
H6175 segment brightness is limited to the global brighness

### ISSUE THREAD

**Issue by Chavife** [wez/govee2mqtt#42]
turning segment brightness is relatively bound to global brightness.

examples:

global brightness: 60%
segment brightness: 100%
resulted segment brightness: 60%
expected segment brightness: 100%

global brightness: 60%
segment brightness: 50%
resulted segment brightness: 30%
expected segment brightness: 50%

**Comment by wez** [comment]
I've added a FAQ that answers this: https://github.com/wez/govee2mqtt/blob/main/docs/FAQ.md
