### ISSUE TITLE
H7171 Kettle Temp and Presets

### ISSUE THREAD

**Issue by angrycatmeowmeow** [wez/govee2mqtt#46]
### Govee Device SKU

H7171

### Govee2MQTT Version

2024.01.10-a8f0a956

### Describe the issue

This G2M update enabled M1 Parameter through M4 Parameter and a temperature entity for my kettle. I purged caches but the M parameters don't report anything useful and the temperature currently displays 0.87 degrees Celsius. It is set to F on the kettle.

### Startup Diagnostics

[2024-01-10T15:37:11 WARN  govee::hass_mqtt::enumerator] Do something about TemperatureSetting sliderTemperature for Teapot (macaddress) DeviceCapability { kind: TemperatureSetting, instance: "sliderTemperature", parameters: Some(Struct { fields: [StructField { field_name: "temperature", field_type: Integer { unit: None, range: IntegerRange { min: 40, max: 100, precision: 1 } }, default_value: None, required: true }, StructField { field_name: "unit", field_type: Enum { options: [EnumOption { name: "Celsius", value: String("Celsius"), extras: {} }, EnumOption { name: "Fahrenheit", value: String("Fahrenheit"), extras: {} }] }, default_value: Some(String("Celsius")), required: true }] }), alarm_type: None, event_state: None }
[2024-01-10T15:37:12 INFO  govee::service::hass] Wait 2.2s for hass to settle on 44 entity configs
[2024-01-10T15:37:15 INFO  govee::service::hass] MQTT connected with status=CONNACK code 0: Connection Accepted.
[2024-01-10T15:37:26 INFO  govee::service::state] requesting update via Platform API Teapot (macaddress) None
[2024-01-10T15:37:26 WARN  govee::hass_mqtt::enumerator] Do something about TemperatureSetting sliderTemperature for Teapot (macaddress) DeviceCapability { kind: TemperatureSetting, instance: "sliderTemperature", parameters: Some(Struct { fields: [StructField { field_name: "temperature", field_type: Integer { unit: None, range: IntegerRange { min: 40, max: 100, precision: 1 } }, default_value: None, required: true }, StructField { field_name: "unit", field_type: Enum { options: [EnumOption { name: "Celsius", value: String("Celsius"), extras: {} }, EnumOption { name: "Fahrenheit", value: String("Fahrenheit"), extras: {} }] }, default_value: Some(String("Celsius")), required: true }] }), alarm_type: None, event_state: None }

### Additional Logs

[mqtt-c15a2879f532decdfcd6788f102863b8-Teapot-3f5fff1b4fe31cf76e9dfdb701c0771c.json (1).txt](https://github.com/wez/govee2mqtt/files/13893869/mqtt-c15a2879f532decdfcd6788f102863b8-Teapot-3f5fff1b4fe31cf76e9dfdb701c0771c.json.1.txt)

### Home Assistant Logs

nothing

### Anything else?

![image](https://github.com/wez/govee2mqtt/assets/67968528/c9d23242-6048-47df-8fe4-0b6408a7f3e0)

**Comment by wez** [comment]
See this issue for ongoing effort to reverse engineer parameters for a similar model.
It's possible that the same parameters and interpretations apply to your model
* https://github.com/wez/govee2mqtt/issues/30

**Comment by wez** [comment]
The temperature shown in your screen shot probably needs to be scaled differently. What is the actual temperature reading in the app?

**Comment by angrycatmeowmeow** [comment]
Unlike in the other thread(I've also owned that kettle), these aren't hard presets, you can change them to anything you want. 
![Screenshot_20240110_162325_Govee Home](https://github.com/wez/govee2mqtt/assets/67968528/c7e00ee3-2852-47bd-a9bd-6d8eba740390)
![Screenshot_20240110_162334_Govee Home](https://github.com/wez/govee2mqtt/assets/67968528/2c16685a-bfd7-4ec9-96eb-a2177dd754df)

**Comment by tankdeer** [comment]
> Unlike in the other thread(I've also owned that kettle), these aren't hard presets, you can change them to anything you want. 

Perhaps it's a newer version of the app, but I can override or delete all the preset modes and replace them with DIYs. 4 per type/setting. This is with the H7173

**Comment by angrycatmeowmeow** [comment]
> > Unlike in the other thread(I've also owned that kettle), these aren't hard presets, you can change them to anything you want.
> 
> Perhaps it's a newer version of the app, but I can override or delete all the preset modes and replace them with DIYs. 4 per type/setting. This is with the H7173

Perhaps. I ended up giving that one to my mom because we needed one that held more water. Def prefer the design of the 7173 but it wasn't big enough for us.

Maybe there's more in common with them than I thought and that will work in our favor.

**Comment by tankdeer** [comment]
I wouldn't be surprised if there's quite a bit in common under the skin. Cost savings and all that. It will definitely help us out though.

**Comment by angrycatmeowmeow** [comment]
Updated to 2024.01.12-108ff95d

M1-M4 can control the presets on the kettle and making changes on the sliders immediately reflects in the Govee app, so setting M1 to 155 will show M1 in the Govee app as 155F. The sliders do not update when a change is made in the Govee app. Backing out of the device and going back in resets the sliders, always to M1-0 M2 & M3-128 and M4-0. The water temperature is displayed in HA with the correct number but shows C instead of F.

This error still present in logs:
[2024-01-13T07:37:28 WARN  govee::hass_mqtt::enumerator] Do something about TemperatureSetting sliderTemperature for Teapot (MACADDRESS H7171) DeviceCapability { kind: TemperatureSetting, instance: "sliderTemperature", parameters: Some(Struct { fields: [StructField { field_name: "temperature", field_type: Integer { unit: None, range: IntegerRange { min: 40, max: 100, precision: 1 } }, default_value: None, required: true }, StructField { field_name: "unit", field_type: Enum { options: [EnumOption { name: "Celsius", value: String("Celsius"), extras: {} }, EnumOption { name: "Fahrenheit", value: String("Fahrenheit"), extras: {} }] }, default_value: Some(String("Celsius")), required: true }] }), alarm_type: None, event_state: None }


![image](https://github.com/wez/govee2mqtt/assets/67968528/79042e23-8be8-4635-a7ff-ba4f2deff0cd)

**Comment by angrycatmeowmeow** [comment]
Everything seems to be working well. I assume the frequency of temperature updates is limited on purpose or by things that are beyond our control. If you want to leave this open you can, or if you need anything further from me let me know, but I am more than satisfied. A huge thank you for all of the work you are putting into this. 
![image](https://github.com/wez/govee2mqtt/assets/67968528/2d802f18-5a59-4743-a3e8-b0702e2065d3)

**Comment by wez** [comment]
Good to hear! One last thing I'd like to do is see if we can give better labels around the presets. If you wouldn't mind following these steps to share the metadata for your device, that will help:

* Then, go to the device entry in for your device
* Find the entity id of the `Status` entity that is listed under your space heater and get its entity name. The default is probably something like `sensor.device_name_status`.

Then evaluate the following home assistant template by visiting Developer Tools | Template, replacing the entity name with what yours actually is:

```
{{
    {
      "meta": state_attr('sensor.space_heater_status', 'platform_metadata'),
      "state": state_attr('sensor.space_heater_status', 'platform_state'),
    }
}}
```

It should output a large-ish json blob, please share that here.

**Comment by angrycatmeowmeow** [comment]
Here you go:

```
{
  "meta": {
    "capabilities": [
      {
        "alarmType": null,
        "eventState": null,
        "instance": "powerSwitch",
        "parameters": {
          "dataType": "ENUM",
          "options": [
            {
              "name": "on",
              "value": 1
            },
            {
              "name": "off",
              "value": 0
            }
          ]
        },
        "type": "devices.capabilities.on_off"
      },
      {
        "alarmType": null,
        "eventState": null,
        "instance": "sliderTemperature",
        "parameters": {
          "dataType": "STRUCT",
          "fields": [
            {
              "dataType": "INTEGER",
              "defaultValue": null,
              "fieldName": "temperature",
              "range": {
                "max": 100,
                "min": 40,
                "precision": 1
              },
              "required": true,
              "unit": null
            },
            {
              "dataType": "ENUM",
              "defaultValue": "Celsius",
              "fieldName": "unit",
              "options": [
                {
                  "name": "Celsius",
                  "value": "Celsius"
                },
                {
                  "name": "Fahrenheit",
                  "value": "Fahrenheit"
                }
              ],
              "required": true
            }
          ]
        },
        "type": "devices.capabilities.temperature_setting"
      },
      {
        "alarmType": null,
        "eventState": null,
        "instance": "sensorTemperature",
        "parameters": null,
        "type": "devices.capabilities.property"
      },
      {
        "alarmType": null,
        "eventState": null,
        "instance": "workMode",
        "parameters": {
          "dataType": "STRUCT",
          "fields": [
            {
              "dataType": "ENUM",
              "defaultValue": null,
              "fieldName": "workMode",
              "options": [
                {
                  "name": "M1",
                  "value": 2
                },
                {
                  "name": "M2",
                  "value": 3
                },
                {
                  "name": "M3",
                  "value": 4
                },
                {
                  "name": "M4",
                  "value": 5
                }
              ],
              "required": true
            },
            {
              "dataType": "ENUM",
              "defaultValue": null,
              "fieldName": "modeValue",
              "options": [
                {
                  "defaultValue": 0,
                  "name": "M1",
                  "value": null
                },
                {
                  "defaultValue": 0,
                  "name": "M2",
                  "value": null
                },
                {
                  "defaultValue": 0,
                  "name": "M3",
                  "value": null
                },
                {
                  "defaultValue": 0,
                  "name": "M4",
                  "value": null
                }
              ],
              "required": false
            }
          ]
        },
        "type": "devices.capabilities.work_mode"
      }
    ],
    "device": "MAC",
    "deviceName": "Teapot",
    "sku": "H7171",
    "type": "devices.types.kettle"
  },
  "state": {
    "capabilities": [
      {
        "instance": "online",
        "state": {
          "value": true
        },
        "type": "devices.capabilities.online"
      },
      {
        "instance": "powerSwitch",
        "state": {
          "value": 0
        },
        "type": "devices.capabilities.on_off"
      },
      {
        "instance": "sliderTemperature",
        "state": {
          "value": {
            "targetTemperature": 100,
            "unit": "Celsius"
          }
        },
        "type": "devices.capabilities.temperature_setting"
      },
      {
        "instance": "sensorTemperature",
        "state": {
          "value": 77
        },
        "type": "devices.capabilities.property"
      },
      {
        "instance": "workMode",
        "state": {
          "value": {
            "workMode": 2
          }
        },
        "type": "devices.capabilities.work_mode"
      }
    ],
    "device": "MAC",
    "sku": "H7171"
  }
}
```

**Comment by wez** [comment]
Thanks; seems like the answer is "no".  I think we can call this one done!
Would you recommend this particular kettle? Our existing kettle is reaching the end of its life, so we're considering what we might get next.

**Comment by angrycatmeowmeow** [comment]
Yeah I don't think you can beat it for the price, and now that it's in HA it's a no brainer. It's holding up well. 

We had the H7173 which is just as good but we sometimes both have a tumbler of black tea in the morning so we needed the higher capacity of the H7171. Got mine automated to start heating when I get up in the morning thanks to this integration, plus some webhook automations to start it from my Shield.

**Comment by wez** [comment]
the amazon listings for both the H7173 and H7171 seem to show the same volume; was the other one that you had a different model, or is there some other aspect that was different?  We like the look of the H7173 slightly better than the H7171, but I'm thinking that the metal construction of the H7171 makes it likely a more durable product for the longer term, and that will probably win out for us over the looks.
