### ISSUE TITLE
Add-on stuck, won't fully load

### ISSUE THREAD

**Issue by angrycatmeowmeow** [wez/govee2mqtt#48]
### Govee Device SKU

N/A

### Govee2MQTT Version

2024.01.10-a8f0a956

### Describe the issue

Saved a snapshot in my H6602 sync box, purged cache and restarted add-on. Add-on will not fully load now and is stuck at the point in the below logs. This makes me wonder, on previous integrations I've had to raise the polling interval, is this a case of me running out of API calls? I have three devices. 

### Startup Diagnostics

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
GOVEE_API_KEY=REDACTED
GOVEE_MQTT_HOST=core-mosquitto
GOVEE_EMAIL=REDACTED
GOVEE_PASSWORD=REDACTED
GOVEE_MQTT_PASSWORD=REDACTED
GOVEE_MQTT_USER=addons
GOVEE_MQTT_PORT=1883
++ cd /app
++ exec /app/govee serve
[2024-01-10T20:53:43 INFO  govee::commands::serve] Starting service. version 2024.01.10-a8f0a956
[2024-01-10T20:53:43 INFO  govee::commands::serve] Querying platform API for device list
[2024-01-10T20:53:43 INFO  govee::commands::serve] Querying undocumented API for device + room list

### Home Assistant Logs

Nothing

**Comment by wez** [comment]
Try setting the debug level to `govee=trace` and restarting the addon to see where it's gotten to.

**Comment by angrycatmeowmeow** [comment]
Current version: 2024.01.10-8beb67bb 

Trace logs below. I wasn't sure what all was sensitive so I redacted everything kinda sensitive looking.

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
GOVEE_API_KEY=REDACTED
GOVEE_MQTT_HOST=core-mosquitto
GOVEE_EMAIL=REDACTED
GOVEE_PASSWORD=REDACTED
GOVEE_MQTT_PASSWORD=REDACTED
GOVEE_MQTT_USER=addons
GOVEE_MQTT_PORT=1883
++ cd /app
++ exec /app/govee serve
[2024-01-11T07:54:45 INFO  govee::commands::serve] Starting service. version 2024.01.10-8beb67bb
[2024-01-11T07:54:45 INFO  govee::commands::serve] Querying platform API for device list
[2024-01-11T07:54:45 TRACE govee::cache] cache hit for device-list
[2024-01-11T07:54:45 INFO  govee::commands::serve] Querying undocumented API for device + room list
[2024-01-11T07:54:45 TRACE govee::cache] cache hit for account-info
[2024-01-11T07:54:45 TRACE govee::service::iot] LoginAccountResponse {
    a: "testiot.cert",
    b: "testIot",
    account_id: REDACTED,
    client: "REDACTED",
    is_savvy_user: true,
    refresh_token: Some(
        "",
    ),
    client_name: Some(
        "",
    ),
    push_token: Some(
        "",
    ),
    version_code: Some(
        "",
    ),
    version_name: Some(
        "",
    ),
    sys_version: Some(
        "",
    ),
    token: "REDACTED",
    token_expire_cycle: 57600,
    topic: "GA/67b56d3df733cb355521b3c205b90b8b",
}
[2024-01-11T07:54:45 TRACE govee::cache] cache hit for iot-key
[2024-01-11T07:54:45 TRACE govee::service::iot] IotKey {
    endpoint: "aqm3wd1qlc3dy-ats.iot.us-east-1.amazonaws.com",
    log: "pro0",
    p12: "MIIJmQIBAzCCCV8GCSqGSIb3DQEHAaCCCVAEgglMMIIJSDCCA/8GCSqGSIb3DQEHBqCCA/AwggPsAgEAMIID5QYJKoZIhvcNAQcBMBwGCiqGSIb3DQEMAQYwDgQILWSeW+FDvAUCAggAgIIDuFmvvHiHdzuByLmEqEr9O0NShzx3NJbjyXKzBaFE54SjZ3mGndQdk/xhKTrpYiOwoSNWLHsp0kK+4Z+ATdIGNwkCWv9pFUHyZtGuAT2BKwgH0JcESRdAcLqV5UZ99AsTRwcdaYGqGvHVuFmpvXkl+FA56QY3t3iyQ7LL5bl07qo+wqoc7nb+xh4l0KjWAvYIheh242LKvUvEk7Cj2wr3o2pMSYaLhb3/wAJkv1f24HXp64D0Li6GvZfzIJI3Zqal3fNvAA9ipHcAnXO53oOmpdAOWEvZU8M4RkSwBe4hOwDeU39E1yogRd+WObxg7r6cUyaS6FdcZHT1hDSYGKZiQwqYOViZDmWA7KbdS0QYPstZM1IqgFob6CWRpiiaNioCBjS5inJAJzv9s3pAkt80wI7+ZCG20RjhG59mrqX4Ogr6AUeiH0IVNBGHBdnv8i1kWKtUcjNPUadjUq4qhIwZ8X9UoHaI3rYpESwVm5B1j07J8BKvwBzlsK/dQ3VuOUkn/QXGirMNkuvpU3VQvIiTiGMcK3uoZ4lwptv4ZkFGZfPBSOevEkYCErKEXMzEzaqEB8gYCHPJQVqcgEqkP9HrW6FxiANqV4bjs1AhZUcTh+tYc1j4ybnftNqGaDscXUA5mwEfZRhsipjBrhJ8lKb9oHoVCu2WfD8qkYgdnXpyGS0hlAFChzzhqqN8nZgoDXF0I1zg8wj1fWfRlzPJRWI1MzIoJA1tb6nhxd//Cf3SaeGYneu5w4CwlqkYF3iX6TfPw5hmxF2NK2c1+I9rpM5b5FevRxNHQAIy2NCkbn2LVy2/kthIUxqZ0IAXbr6AVOQnZiBz4UDSA7bkZOdOLg10VXDnhgink1CpYJsCVl9W1Uoa9wBrj1cmWsdVaoxWkOzoBUgT3ZylihBn+wa+UvxIDq7H1c9subsJve0pVylO3cFdS6Y3lH/hfRf/5jBOsB/mOzI4n9x/KQsn6qt2e2RZ0o5t9J6klX/fKa2kYz0lWP7f1pU7USpFhNnQzl972sCBmkjnHn/OntBlyWvw3Mx1AHR6hH034f+qfym0oD1MOuaFls0lHEnF7yxxX66hgnZpUDNsYEwamwHcVd9poKIHhXrTPL5Aa0f8YUkyYYi0xa4PB4oMMJcYARa0pRuv0kBF6OsP0QPTAevzB3rzUlf3SeIbKVmpmhEFfF9WG6UWG/fhOwo4F4AIk/b6mhio72XmZp615JEK2Fml9GsNyj91iVjDvVqhNL9rVsuUipaotYH/X7iqFGOAYR0wggVBBgkqhkiG9w0BBwGgggUyBIIFLjCCBSowggUmBgsqhkiG9w0BDAoBAqCCBO4wggTqMBwGCiqGSIb3DQEMAQMwDgQIIXa5ahQj9MACAggABIIEyNU3MBDs8wel9UsBBXprqPAbfABY8aFHIF125EPA8ART1TaWUASrYIM107tt+d3BlHSsRVjBvhDhIkryqIq6jG9Nh8rp61x6D2iA+5Rlla6JBvZgMVzN77qOE0tMI19OsPaB4u67znD00djTqxpsFYDGaxUbxmO6LeDZHQvJ+QqupP1rsqylEC30T4SNIJZEWyC+T9kKhJfp4DvWLtSYdehdW28x2nMXmStvXh/D08Q/+A0ihudKUDyrLG6cWaOmTcMWGpmMSyFyoTo5tIv1AX4RgPx4Mhty/WX/JoPzfPIdeyBnqXxhnBIoyekP1R0QXmXdD7Z7+vhW0h/YIStVwQqZ3ZpuIeGZCpoDBEM5pPraUv8NoIXXcZ5Q/JVE0GsHjPKY2AHx5k8aByNFzMRQfPlwDF3crQcVGO4K8SKfRI6Bgooy4DWyWHapNtQ7gLxx+eJfz6wXSBTh3egC2dGZZPz6AqpvyAE3LR52tUyoMYxVDL0UlV0oX1Hj9zBWwUbMpmyIYByFFcpv7pTy00O13soyfNrYe1DBQ/4t6vKoWPhaCQza8wHVRvvxfQuyD8krzzeuQnujk76EWGUPvA+pTnxVMqZIcYnDMsIt34XRBHJs84IapmMxdidp/U1M8duGoP0HdvZCLWbQ6uhO95ac2DThnTHmATEDqglW+UE4+d+E89kLAu8BwK4Cov1W5m9u2uF/rE5G5aEzq9LiGGAz5ymY2EOJc3wXYcRSLscQiCc3EgjpcutTypG9IHigmf9aPex19XI3G+URd2KTWKinVSC6V7BkTO+kRgi5JBxOEcTH46WROo3ErqCSYEKt2zCP5WXc3ph3dZrAiq4tY4xQQIVzKlQmwwWxZ4ciaY7yPirhAUU9z588A0gAbCO+QR8TP2PYsuL6bFYf1lEABPwD0b1+EzJdNbvTPLn5JH45BrvBqIdbFeoPRLlzcO4JbEGhF8+CW7qGz8cTRSQL4+H84rDLHHM3X7r9wnD2BK3U7zQJCqR0Aw5xAlzkVMXZvQpLerWAwIqMF0qHilTa2soZRBzxSzScadGPgMeVOMHHHnX91gWQ5ncr2twpu9HuHCTr2iTz5GhYuFGXEPRrFm/yjwuW8vGZNJHI/cIZMGAIpiQ6TDU8y3y18Hf6r813H4OM9GtWU9NRxFGGu4OnBZP37s00O69R5fPbL137fIH/bbIIf8lvA31PELm7yoI4g29c2uNVkLgVGqCnZQNbDCNUvJjexaEyZDnkSIwk0RIEt8Ga5UggC12ki3Q9Ac8VJa7YpiQJ458/OEAXlDT6a7fKOr4YRcEmyeqC/bn8mqXfDK5vpgh+q0GJlaGuZO5KjKQOYC4IS4DRCPtvl0jM9ganVWdryCa/GW6kIyWXVycloOi+0MefopNWChKtZleWTRwwLgVGsEqhWBhRke3Mb43oCkXi8sUnLKMxZTZTznGf3MiXnf1LGrT3KrOq3BG++Oy2jEYpD4szLGdL/g7qLGRpf8HWJSlKG/Hh6SzrItW8ECg/A9LDBw5S+k4zr+FZjdzVXkWM0livgJfx9MlsTXktTi8Fhb9JwkYWFZ9jlPDQmFqhXKXMRS6gX/RKBU5UFR23A4OirftnhYOftQIjsr3wp0SpZ+9r6rAnFTElMCMGCSqGSIb3DQEJFTEWBBSmdVAs6pk4eGfVJ5PVhuWiWlF2ADAxMCEwCQYFKw4DAhoFAAQUKUf0BtU0OyVUy1sGK+34Nrh/UmwECNdxJxNsdtcxAgIIAA==",
    p12_pass: "REDACTED",
}

**Comment by wez** [comment]
I suspect that it is unable to connect to `aqm3wd1qlc3dy-ats.iot.us-east-1.amazonaws.com:8883` for the IoT connection.
Is that system able to connect to the public internet?
I'll push an updated build with an explicit timeout around the connection attempt so that we can see if this is the case more easily.

**Comment by wez** [comment]
Please update the addon and let's see what happens

**Comment by angrycatmeowmeow** [comment]
This domain is not blocked in Adguard Home and none of the devices are blocked from accessing the internet.

Updated the addon and it's working again. All devices are there and controllable.

Still not getting my snapshot (tap to run) for video mode on my AI sync box as a scene in HA, but that's a separate issue I suppose.

**Comment by wez** [comment]
hmm, well, I suppose it was a transient connectivity issue then. Let's close this; please open a separate issue for the tap to run scene
