### ISSUE TITLE
Effects does not work with scenes

### ISSUE THREAD

**Issue by marcelpetersen** [wez/govee2mqtt#5]
If Im creating a scene and apply a scene to a govee device, the effect will not be triggered.
In the preview mode, I can see the scene gets applied. But if im triggering the scene, nothing happens.

In the scenes.yaml the effect entry is empty. Already tried to set it manually, but without any success

**Comment by wez** [comment]
Hmm, I think this is because Govee's API doesn't report the currently active effect, so therefore we can't report it to hass, which means that it won't show up in the hass scene metadata.

**Comment by wez** [comment]
The latest update should improve how this works!

**Comment by marcelpetersen** [comment]
Can confirm that it is working for now. Thanks!

**Comment by wez** [comment]
Great!

**Comment by Rustymage** [comment]
I don’t see the effect memory working. I apply an effect and it’s not reflected in any way I can see - could you point me at where to find it please?
