### ISSUE TITLE
Addon keeps stopping. No devices in MQTT.

### ISSUE THREAD

**Issue by Czechmarty** [wez/govee2mqtt#54]
### Govee Device SKU

H7021, H7060, H705C, and more

### Govee2MQTT Version

2024.01.11-6a00caa3 

### Describe the issue

Addon keeps stopping. No devices in MQTT.
Plugin configured, but when I hit start, it attempts to start then shuts down. Please see log.

### Startup Diagnostics

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
GOVEE_API_KEY=REDACTED
GOVEE_MQTT_HOST=192.168.2.8
GOVEE_EMAIL=REDACTED
GOVEE_PASSWORD=REDACTED
GOVEE_MQTT_PASSWORD=REDACTED
GOVEE_MQTT_USER=
GOVEE_MQTT_PORT=
++ cd /app
++ exec /app/govee serve
[2024-01-11T15:47:57 INFO  govee::commands::serve] Starting service. version 2024.01.11-6a00caa3
[2024-01-11T15:47:57 INFO  govee::commands::serve] Querying platform API for device list
[2024-01-11T15:47:58 INFO  govee::commands::serve] Querying undocumented API for device + room list
Error: request https://app2.govee.com/device/rest/devices/v1/list status 200: OK

Caused by:
    0: parsing https://app2.govee.com/device/rest/devices/v1/list response
    1: govee::undoc_api::DevicesResponse devices[8].deviceExt.deviceSettings: govee::undoc_api::DeviceSettings govee::undoc_api::DeviceSettings wifiLevel: invalid value: integer `-100`, expected u8 at line 1 column 192. Input: {"temMin":1555,"temMax":2944,"temWarning":true,"fahOpen":true,"temCali":0,"humMin":0,"humMax":10000,"humWarning":false,"humCali":0,"netWaring":true,"uploadRate":10,"battery":1,"wifiLevel":-100,"bleName":"Govee_H5071_C435","address":"E0:12:1C:30:C4:35","secretCode":"B2DC89E360EA37F1","sku":"H5071","device":"C2:08:E0:12:1C:30:C4:35","deviceName":"Bedroom Temperature","versionHard":"1.03.00","versionSoft":"1.06.02"} while processing embedded json text 

Stack backtrace:
   0: anyhow::error::<impl anyhow::Error>::msg
   1: govee::platform_api::from_json
   2: govee::undoc_api::GoveeUndocumentedApi::get_device_list::{{closure}}
   3: govee::commands::serve::ServeCommand::run::{{closure}}
   4: govee::Args::run::{{closure}}
   5: tokio::runtime::park::CachedParkThread::block_on
   6: tokio::runtime::runtime::Runtime::block_on
   7: govee::main
   8: std::sys_common::backtrace::__rust_begin_short_backtrace
   9: std::rt::lang_start::{{closure}}
  10: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:284:13
  11: std::panicking::try::do_call
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40
  12: std::panicking::try
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19
  13: std::panic::catch_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14
  14: std::rt::lang_start_internal::{{closure}}
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:148:48
  15: std::panicking::try::do_call
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40
  16: std::panicking::try
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19
  17: std::panic::catch_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14
  18: std::rt::lang_start_internal
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:148:20
  19: std::rt::lang_start
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

### Additional Logs

N/A

### Home Assistant Logs

Nothing

**Comment by wez** [comment]
Should be resolved in the latest version of the addon; please update and let me know!

**Comment by Czechmarty** [comment]
You are awesome!! Works now like a charm!!!!
