### ISSUE TITLE
API Key not 100% local

### ISSUE THREAD

**Issue by JonSnow88** [wez/govee2mqtt#66]
### Govee Device SKU

H619C

### Govee2MQTT Version

latest

### Describe the issue

I have Govee2MQTT working perfectly while the light strips have access to the internet, but as soon as I move it to my other network that does not have internet access G2M stops working. The addon shows they are connected, and I can see them on my wifi but the lights do not respond to any commands.

This may not be G2M problem as I noted Lan Control option disappears and wifi status shows disconnected on the app as it's moved to another VLAN with no internet, if I move it back to my main LAN the option comes back and the wifi status shows connected.

### Startup Diagnostics

attempted this mutiple times, restarted HA and all addons just to be sure it is not an issue on my end. I have allot of devices configured this way so it is not my network.

**Comment by JonSnow88** [comment]
I retest again and this time was able to get the Lan Control option to work and can confirm it did indeed work 100% offline.

But lost the ability to apply effects, this was the case in G2M as well as the Govee desktop app. 

So I guess effects are over internet or bluetooth?

**Comment by wez** [comment]
There's a table that should explain which features require which APIs here in the readme: 
https://github.com/wez/govee2mqtt#features

**Comment by wez** [comment]
And for clarity: any API other than the LAN API requires both HASS and your devices to have an internet connection.
