### ISSUE TITLE
Support for scenes over IoT API

### ISSUE THREAD

**Issue by rygwdn** [wez/govee2mqtt#7]
Would it be possible to support getting and activating scenes or "one click shortcuts" over the IoT API, and force the addon to use that API rather than the official one for certain devices? I have an H610A which doesn't report any functionality other than on/off from the official API despite being full RGBIC (reported to Govee [here](https://developer.govee.com/discuss/656fd9edd3052d006ce3d8f5) without much luck). The scenes can be activated with homebridge-govee with some manual setup, so I believe it's possible over the IoT API.

Thanks for the awesome work on this!

**Comment by wez** [comment]
I'll take a look. As it happens, I also have an H610A but I didn't notice this because I replaced it with a more beefy home made strip(!) and it's been sitting in the corner.

I do have some logic to read the "one click shortcuts", but it is a bit murky to try to reverse engineer most of those.

I also recently did some reverse engineering around scenes and getting things to work via the LAN API: https://github.com/egold555/Govee-Reverse-Engineering/issues/11 I'm not sure that it works for 100% of all scenes, but it might be enough to satisfy you.

**Comment by rygwdn** [comment]
I can actually pull DIY scenes and the built-in dynamic scenes for the device via the official API (`/router/api/v1/device/scenes` and `/router/api/v1/device/diy-scenes`) it just doesn't report that the device is capable of receiving those commands, and refuses to accept them if I try.

**Comment by wez** [comment]
I just pushed some basic improvements for this device; you can now control the color and brightness.
It does also have limited support for scenes; in practice, it is just scenes with scene codes in the range 1-255.
Scenes like Breathe and Rainbow work for me with this for example.

I'll need to do some more digging to see about enabling things like the one-click shortcuts.

**Comment by wez** [comment]
I just pushed a version that now adds a home assistant scene for each One Click you have defined in the app.
You can find them under "Settings > Automations and Scenes > Scenes".

**Comment by rygwdn** [comment]
Thank you! It works perfectly 🎉 I can finally get rid of my homebridge server I was running just for this functionality 😄 . Hopefully the official API and/or LAN API get support for this at some point, but this is an excellent workaround.

**Comment by rygwdn** [comment]
would it be possible to have the one-click scenes show up as effects under the relevant devices as well? Don't worry about it if it's complicated!

**Comment by wez** [comment]
it's a bit awkward to add to the effects list for a couple of reasons:
* one-click scenes are potentially multi-device, which feels like a bit of a mismatch in intent for per-device effects
* figuring out that an effect is a one-click scene would have to resort to some icky string checks and the jumping across layers in the code to actually execute it

What may be a bit easier to fit in is adding a button for each scene the device belongs to, which would show up similarly to how the scenes show up in the `Govee to MQTT` virtual device, but for the light in question:

![image](https://github.com/wez/govee2mqtt/assets/117777/576eb0e4-175d-419f-832e-176df23ac60a)

I wonder if I can make this automatically happen without adding additional entities; if there is some way to associate the scene entity with the device(s) that belong to it, then the default behavior of showing the scenes in the UI should kick in.  Again, this is visible with the `Govee to MQTT` virtual device:

![image](https://github.com/wez/govee2mqtt/assets/117777/c51486db-26d3-4c4a-acb0-f2a7ef8dbe18)

**Comment by rygwdn** [comment]
My goal was to be able to add the govee scene as part of a larger HA scene (e.g. have a HA scene that triggers a govee scene/one-click and also applies other settings for other devices). Some kind of button or switch might work for that..

**Comment by wez** [comment]
you could create a home assistant script that triggers both the home assistant scene that you create and the one click scene(s)

**Comment by rygwdn** [comment]
Looks like they fixed the platform API for my H610A, so the quirks may no longer be needed for it!

**Comment by wez** [comment]
Confirmed: I can set all the scenes for mine here with that quirk override removed

**Comment by wez** [comment]
@rygwdn latest version removes the quirk, enjoy!
