### ISSUE TITLE
It's working great for me so far.... Any idea on how to get it to react to music for devices with built in mics....

### ISSUE THREAD

**Issue by wez** [wez/govee2mqtt#8]
It's working great for me so far.... Any idea on how to get it to react to music for devices with built in mics....

Here's an example of the music scenes I'm looking for in the govee app

<img src="https://github.com/wez/govee-lan-hass/assets/50434137/53040409-b027-4dfe-b209-1cf27aeaac6b" width="50%">

_Originally posted by @superpunkduck in https://github.com/wez/govee-lan-hass/issues/50#issuecomment-1877807772_

**Comment by wez** [comment]
In about 10 minutes or so (when https://github.com/wez/govee2mqtt/actions/runs/7415700466 completes), try updating the addon and you should see some effects prefixed with `Music: ` in the list of effects.
Those are music modes with sensitivity set to 100.

**Comment by superpunkduck** [comment]
I'm not seeing any option to update the addon... And the changelog is empty.
![Screenshot_20240104-194649](https://github.com/wez/govee2mqtt/assets/50434137/fa2b4892-d94d-4c39-85cc-5c03bf7404cd)
![Screenshot_20240104-194654](https://github.com/wez/govee2mqtt/assets/50434137/fe8c017f-13f2-4394-a8b9-8e0139182e6f)

**Comment by superpunkduck** [comment]
I can see the update now...but it wont update.. see screenshot
![image](https://github.com/wez/govee2mqtt/assets/50434137/19de85ae-a82c-459a-83ab-31446a0da0cf)

**Comment by wez** [comment]
bear with me; I'm trying to persuade some CI stuff into working properly

**Comment by wez** [comment]
OK, I think it should be working now; click on the check for updates icon in the addons section. Not sure how that looks in the mobile app, but in the browser:

![image](https://github.com/wez/govee2mqtt/assets/117777/2cf50446-9df2-4e6f-8ec1-b855bfd23359)

`2024.01.04-a76b0bbf` is the version you want it to show as available, and updating to that should work.

**Comment by superpunkduck** [comment]
> OK, I think it should be working now; click on the check for updates icon in the addons section. Not sure how that looks in the mobile app, but in the browser:
> 
> ![image](https://private-user-images.githubusercontent.com/117777/294393325-2cf50446-9df2-4e6f-8ec1-b855bfd23359.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NzA0NDksIm5iZiI6MTcwNDQ3MDE0OSwicGF0aCI6Ii8xMTc3NzcvMjk0MzkzMzI1LTJjZjUwNDQ2LTlkZjItNGU2Zi04ZWMxLWI4NTViZmQyMzM1OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNVQxNTU1NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMzM5ZTRjZTk3NTEwNzMyMTZmMzRlYTczZDQxNjA4MmFmZTk1YmVmNDEzM2IyNjVkNzg0YmVkZjdmZjRhNjI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EbXEHLmVc5WAWKpMLYXji6P9kdAqtBbTBr2lvEg9MrQ)
> 
> `2024.01.04-a76b0bbf` is the version you want it to show as available, and updating to that should work.

It working...You're a Wizard!

**Comment by wez** [comment]
Yay!
