### ISSUE TITLE
Feature Request: MQTT topic human readable

### ISSUE THREAD

**Issue by TommyJW** [wez/govee2mqtt#9]
Currently the MQTT topic is based on the UUID from the strip. While we can use the discovery / config payload to retrieve a human-readable name and store that somewhere, it may be easier long-term to use some other human-readable name.

Perhaps govee2mqtt could request the home assistant entity ids?

Reason for request:
I'm using NodeRed with the HomeAssistant nodes. Lights and MQTT nodes do not auto-populate the Effects options. So I started using the built-in mqtt out node which would require knowing the uuid topics for each device in advance. This could be a bit of maintenance overhead as devices come online or are replaced.
Open for suggestions on how to automate the retrieval of the discovery payload to create a map of sorts.

**Comment by wez** [comment]
For MQTT we have to use a stable identifier, and that identifier has be a valid MQTT topic name. We don't really have a choice but to derive the topic name from the device ID; it is the only identifier available to the LAN API, and the LAN API does not provide the more friendly names.

If your goal is to send commands to the lights then you may be interested to know that there is a REST API that is a bit more flexible in what it accepts for identifiers, although you will need to escape the relevant parts of the URL.  You can use the device ID or its friendly name, and those are matched case insensitively.

For example, this sets a light to blue. You can use most CSS compatible color syntaxes for this:

```console
$  curl http://hostname:8056/api/device/my%20device%20name/color/blue
{"code":200,"msg":"ok"}
```

Here's a list of the routes; hopefully those are easy enough to grasp without additional docs

https://github.com/wez/govee2mqtt/blob/1e03a39ff98bfc9e81d9cdf30034a78a740287f1/src/service/http.rs#L187-L200

**Comment by wez** [comment]
Can you share a bit more about what you're trying to do?

**Comment by TommyJW** [comment]
One concrete objective is this:
Have bed with two presence sensors. Have govee light strips under each side of the bed.
At 9:00pm turn on Govee Dream scene for 1 hour on both strips.
Between 10:00pm and 6:00am if presence not detected on one side of bed, illuminate only that corresponding strip Red 5%.
Between 10:00pm and 6:00am if presence detected, and light red, turn light to 0%
At 6:00am turn on Govee Sunrise scene on both strips.

Other lights around the home may be affected in the future based on time and presence for either side of the bed.

So, I was hoping to abstract the UUID from that flow. Currently, the NodeRED nodes I'm aware of do not have a method to say something clear like:
Call Service - light - Set Scene - Dream - Device - Side A Govee Strip
Instead it has to be:
Call MQTT - Topic gv2mqtt/light/:uid/command, payload {"state":"ON","effect":"Sunrise"}

Now I could make a map of name -> uid and do a replacement just before the call MQTT node. That way each sensor trigger could be aware of its light strip side (and future other strips) as human readable names, then the map could do the replacement. But if there is an existing, elegant solution, I'm certainly interested that. I can see 6 months from now me might have a problem remembering which UID goes to which light, or tracking down the map and means to add/modify new entries.

The REST API does sound nice. I don't particularly like that it has a dependency on the naming convention within the Govee app. I tend to think of the ecosystem-specific naming (govee, switchbot, Lutron) as error prone since they aren't in one centralized location like the Home Assistant Device panel.

**Comment by wez** [comment]
I just tried this topic via mqtt and it worked:

`gv2mqtt/light/study floor lamp 1/command`

So, provided that your govee-app-assigned device names don't have illegal-to-mqtt-topic characters embedded in them, you can use more meaningful names this way.

> I don't particularly like that it has a dependency on the naming convention within the Govee app.
> ... since they aren't in one centralized location like the Home Assistant Device panel.

Well, that is difficult to handle in the context of govee2mqtt. While it is intended to work with home assistant,
it doesn't have any dependency upon home assistant.

Home assistant derives entity and device names from the information provided by govee2mqtt, which in turn come from Govee's server state, but doesn't pass either its chosen name (there's no guarantee that what we suggest is what it uses) or the names that the user chose back to us.

Short of building out some kind of home assistant API scraper to try to find our entities and reverse engineer the names (which is undesirable: it doesn't scale well for systems with a lot of entities and it makes it more awkward for running as an addon), there's no way for us to know this.

Now, taking a step back: if you want to control entities based on the naming in HASS, have you considered using the HASS API to do this?  You can issue a `light.turn_on` service call using your chosen entity name for example.

**Comment by TommyJW** [comment]
> Now, taking a step back: if you want to control entities based on the naming in HASS, have you considered using the HASS API to do this? You can issue a light.turn_on service call using your chosen entity name for example.

Thank you!
When I looked at the node last night, I was strictly thinking of turn.on in the context of ON/OFF, and didn't think about the options passed in the data field.

I can use a call service instead of the MQTT node and fully solve my issue. Marking as closed. Thanks again for the time and support.
