### ISSUE TITLE
H5179 quirks

### ISSUE THREAD

**Issue by rixls** [wez/govee2mqtt#95]
### Govee Device SKU

H5179

### Govee2MQTT Version

2024.01.19-ffca9c12

### Describe the issue

The H5179 wifi thermometer/hygrometer reports temperature (C) and humidity (%) scaled by 100

### Startup Diagnostics

```
[2024-01-20T16:16:16 INFO  govee::commands::serve] Wifi Thermometer (78:80:18:1F:C7:94:69:51 H5179)
[2024-01-20T16:16:16 INFO  govee::commands::serve]   Platform API: devices.types.thermometer. supports_rgb=false supports_brightness=false
[2024-01-20T16:16:16 INFO  govee::commands::serve]                 color_temp=None segment_rgb=None
[2024-01-20T16:16:16 INFO  govee::commands::serve]   Undoc: room=Some("Home") supports_iot=false ble_only=true
```

### Anything else?

Tysm for your hard work on this impressive integration!

**Comment by wez** [comment]
Please share the metadata for your device:

* go to the device entry in for your device
* Find the entity id of the `Status` entity that is listed under your space heater and get its entity name. The default is probably something like `sensor.device_name_status`.

Then evaluate the following home assistant template by visiting `Developer Tools` | `Template`, replacing the entity name with what yours actually is:

```
{{
    {
      "meta": state_attr('sensor.device_name_status', 'platform_metadata'),
      "state": state_attr('sensor.device_name_status', 'platform_state'),
    }
}}
```

It should output a large-ish json blob, please share that here.

**Comment by rixls** [comment]
```
{
  "meta": {
    "capabilities": [
      {
        "alarmType": null,
        "eventState": null,
        "instance": "sensorTemperature",
        "parameters": null,
        "type": "devices.capabilities.property"
      },
      {
        "alarmType": null,
        "eventState": null,
        "instance": "sensorHumidity",
        "parameters": null,
        "type": "devices.capabilities.property"
      }
    ],
    "device": "78:80:18:1F:69:51:CC:94",
    "deviceName": "Wifi Thermometer",
    "sku": "H5179",
    "type": "devices.types.thermometer"
  },
  "state": {
    "capabilities": [
      {
        "instance": "online",
        "state": {
          "value": true
        },
        "type": "devices.capabilities.online"
      },
      {
        "instance": "sensorTemperature",
        "state": {
          "value": 2150
        },
        "type": "devices.capabilities.property"
      },
      {
        "instance": "sensorHumidity",
        "state": {
          "value": {
            "currentHumidity": 3310
          }
        },
        "type": "devices.capabilities.property"
      }
    ],
    "device": "78:80:18:1F:69:51:CC:94",
    "sku": "H5179"
  }
}
```

**Comment by wez** [comment]
Thanks; this should be taken care of in the latest version available now!

**Comment by rixls** [comment]
Looks great, thanks again!

**Comment by buschtoens** [comment]
I believe this change may have been incorrect. Quite a few people (including me) suddenly saw correct readings take a dip and reported it in https://github.com/wez/govee2mqtt/issues/149#issuecomment-2005550569.

I'm getting the following readings from my `H5179` with `2024.01.24-ea3cd430`:

- `sensorTemperature`: `79.52` (in Fahrenheit, not scaled by 100)
- `sensorHumidity`: `35` (in percent, not scaled by 100)

<details>
<summary>Full template output</summary>

```json
{
  "meta": {
    "capabilities": [
      {
        "alarmType": null,
        "eventState": null,
        "instance": "sensorTemperature",
        "parameters": null,
        "type": "devices.capabilities.property"
      },
      {
        "alarmType": null,
        "eventState": null,
        "instance": "sensorHumidity",
        "parameters": null,
        "type": "devices.capabilities.property"
      }
    ],
    "device": "93:16:18:CE:B8:C0:C9:12",
    "deviceName": "Balcony",
    "sku": "H5179",
    "type": "devices.types.thermometer"
  },
  "state": {
    "capabilities": [
      {
        "instance": "online",
        "state": {
          "value": true
        },
        "type": "devices.capabilities.online"
      },
      {
        "instance": "sensorTemperature",
        "state": {
          "value": 79.52
        },
        "type": "devices.capabilities.property"
      },
      {
        "instance": "sensorHumidity",
        "state": {
          "value": {
            "currentHumidity": 35
          }
        },
        "type": "devices.capabilities.property"
      }
    ],
    "device": "93:16:18:CE:B8:C0:C9:12",
    "sku": "H5179"
  }
}
```

</details>

The addon is configured to use the Celsius (`C`) temperature scale, in case that is relevant.

Below is a screenshot showcasing the issue:

- The temperature is NOT converted from Fahrenheit to Celsisus AND is incorrectly scaled down by factor 100.
  For instance: `0.8` in the graph maps to 80 ℉, which is the exepected 26.6 ℃.
- The humidity is scaled down by factor 100 and ranges between `0.00` and `1.00` instead of the correct `0` and `100`.

![image](https://github.com/wez/govee2mqtt/assets/834636/ff5704e7-752c-430c-89b8-750a12be776d)
